#!/usr/bin/env python3
from pathlib import Path

italian = {
    'Format': 'Formato', 'Best For': 'Migliore per', 'Quality Options': 'Opzioni di qualità', 'File Size': 'Dimensione file',
    'Universal audio playback': 'Riproduzione audio universale', 'Small': 'Piccolo', 'Video playback everywhere': 'Riproduzione video ovunque',
    'Large': 'Grande', 'Lossless audio editing': 'Editing audio senza perdita', 'Very Large': 'Molto grande', 'Apple devices': 'Dispositivi Apple',
    'Native AAC': 'AAC nativo', 'Medium': 'Medio', 'Batch Conversion Masterclass': 'Masterclass di conversione batch',
    'Preserve Original Order and Titles': 'Preserva ordine e titoli originali', 'Flexible Format Selection for Playlists': 'Selezione formato flessibile per playlist',
    'High-Concurrency Processing': 'Elaborazione ad alta concorrenza', 'Support for Massive Playlists': 'Supporto per playlist massive',
    'Download Auto-Generated Mixes': 'Scarica mix generati automaticamente', 'Ideal for Educators and Students': 'Ideale per educatori e studenti',
    'Handling Unavailable or Private Videos': 'Gestione di video non disponibili o privati', 'How to Download a Full Playlist': 'Come scaricare una playlist completa',
    'Downloading videos one by one is incredibly tedious. Our YouTube Playlist Downloader is engineered for bulk operations. By parsing the playlist metadata, our servers generate individual conversion jobs for every single video in the list, allowing you to download an entire album, lecture series, or podcast backlog with minimal effort.': 'Scaricare video uno per uno è incredibilmente noioso. Il nostro YouTube Playlist Downloader è progettato per operazioni in blocco. Analizzando i metadati della playlist, i nostri server generano lavori di conversione individuali per ogni singolo video nell\'elenco, consentendoti di scaricare un intero album, serie di lezioni o arretrato di podcast con il minimo sforzo.',
    'When you download a playlist, organization is key. Our system automatically grabs the original video titles and structures the downloads so you can easily maintain the intended order. This is perfect for sequential tutorials, multi-part documentaries, or chronologically ordered music albums.': 'Quando scarichi una playlist, l\'organizzazione è fondamentale. Il nostro sistema cattura automaticamente i titoli video originali e struttura i download in modo da poter facilmente mantenere l\'ordine previsto. Questo è perfetto per tutorial sequenziali, documentari in più parti o album musicali ordinati cronologicamente.',
    "You aren't locked into a single format. You can choose to download an entire music playlist as crisp 320kbps MP3s, or an entire educational course as 1080p MP4s. Our FFmpeg backend applies your selected format uniformly across all items in the batch.": 'Non sei bloccato in un singolo formato. Puoi scegliere di scaricare un\'intera playlist musicale come MP3 nitidi a 320kbps, o un intero corso educativo come MP4 a 1080p. Il nostro backend FFmpeg applica il formato selezionato uniformemente su tutti gli elementi nel batch.',
    "We don't make you wait for one video to finish before starting the next. Our cloud infrastructure utilizes high-concurrency processing, meaning multiple videos from your playlist are downloaded and converted simultaneously. A 50-video playlist is processed significantly faster than doing it manually.": 'Non ti facciamo aspettare che un video finisca prima di iniziare il successivo. La nostra infrastruttura cloud utilizza l\'elaborazione ad alta concorrenza, il che significa che più video dalla tua playlist vengono scaricati e convertiti simultaneamente. Una playlist di 50 video viene elaborata significativamente più velocemente che farlo manualmente.',
    "Whether it's a 10-track EP or a massive 300-video mega-mix, our tool is built to handle it. While extremely large playlists may take a few minutes to fully parse and render download buttons, our backend will not time out or crash during the operation.": 'Che si tratti di un EP da 10 tracce o di un massiccio mega-mix da 300 video, il nostro strumento è costruito per gestirlo. Mentre le playlist estremamente grandi potrebbero richiedere alcuni minuti per essere completamente analizzate e renderizzare i pulsanti di download, il nostro backend non andrà in timeout o si bloccherà durante l\'operazione.',
    "Did YouTube's algorithm create the perfect 'My Mix' or 'Discover Weekly' equivalent for you? Just copy the URL of that auto-generated playlist and paste it here. You can rip the entire curated mix to your local device for offline listening on road trips or flights.": "L'algoritmo di YouTube ha creato il perfetto equivalente di 'My Mix' o 'Discover Weekly' per te? Copia semplicemente l'URL di quella playlist generata automaticamente e incollala qui. Puoi copiare l'intero mix curato sul tuo dispositivo locale per l'ascolto offline durante viaggi in auto o voli.",
    'Many professors and online instructors organize their course modules into public YouTube playlists. Students can use our tool to download the entire semester\'s worth of lectures in MP4 format, ensuring they have access to study materials even without an internet connection.': 'Molti professori e istruttori online organizzano i loro moduli di corso in playlist YouTube pubbliche. Gli studenti possono utilizzare il nostro strumento per scaricare le lezioni di un intero semestre in formato MP4, assicurandosi di avere accesso ai materiali di studio anche senza connessione Internet.',
    "Playlists often contain videos that have been deleted, made private, or restricted in your region. Our parser intelligently skips these dead links and continues processing the available videos, so your batch download isn't ruined by a single broken link.": 'Le playlist spesso contengono video che sono stati eliminati, resi privati o limitati nella tua regione. Il nostro parser salta intelligentemente questi link morti e continua a elaborare i video disponibili, quindi il tuo download in batch non viene rovinato da un singolo link rotto.',
    "1. Navigate to the playlist on YouTube. Ensure the URL contains 'list=' (e.g., youtube.com/playlist?list=...). 2. Copy the URL. 3. Paste it into our converter. 4. Select your global format (MP3 or MP4). 5. Click Convert. 6. Wait for the parser to extract the videos, then click the individual download buttons as they appear.": "1. Naviga alla playlist su YouTube. Assicurati che l'URL contenga 'list=' (ad es., youtube.com/playlist?list=...). 2. Copia l'URL. 3. Incollalo nel nostro convertitore. 4. Seleziona il tuo formato globale (MP3 o MP4). 5. Fai clic su Converti. 6. Attendi che il parser estragga i video, quindi fai clic sui singoli pulsanti di download man mano che appaiono.",
    'Is there a maximum playlist length?': 'C\'è una lunghezza massima della playlist?', 'Are playlists downloaded in order?': 'Le playlist vengono scaricate in ordine?',
    'Is there a limit to the number of videos in a playlist?': 'C\'è un limite al numero di video in una playlist?', 'Will it download as one giant file or separate files?': 'Verrà scaricato come un file gigante o file separati?',
    "Can I download a 'Watch Later' playlist?": "Posso scaricare una playlist 'Guarda più tardi'?", 'What happens if the playlist contains a live stream?': 'Cosa succede se la playlist contiene un live stream?',
    'How long does a 50-video playlist take to convert?': 'Quanto tempo impiega una playlist di 50 video a convertirsi?', 'Do I have to click download 50 times?': 'Devo fare clic su scarica 50 volte?',
    'Does it download the playlist thumbnail?': 'Scarica la miniatura della playlist?', "Can I download a channel's entire video list?": 'Posso scaricare l\'intero elenco video di un canale?',
    'Are the files numbered?': 'I file sono numerati?', 'Why did only half the videos appear?': 'Perché è apparsa solo metà dei video?',
    'No hard cap, but very large playlists (500+ videos) may take several minutes to process in full.': 'Nessun limite rigido, ma le playlist molto grandi (oltre 500 video) potrebbero richiedere diversi minuti per essere elaborate completamente.',
    'Yes. Original playlist ordering is preserved by default.': 'Sì. L\'ordine originale della playlist è preservato per impostazione predefinita.',
    'We can theoretically parse playlists of any size, but for optimal performance and browser stability, we recommend downloading playlists with 200 videos or fewer at a time.': 'Possiamo teoricamente analizzare playlist di qualsiasi dimensione, ma per prestazioni ottimali e stabilità del browser, consigliamo di scaricare playlist con 200 video o meno alla volta.',
    'Each video in the playlist is converted and downloaded as its own separate file. We do not merge them into a single massive audio/video file.': 'Ogni video nella playlist viene convertito e scaricato come file separato. Non li uniamo in un singolo file audio/video massiccio.',
    "Your 'Watch Later' playlist is private to your account. Our servers cannot access it. You would need to move those videos to a Public or Unlisted playlist first.": "La tua playlist 'Guarda più tardi' è privata per il tuo account. I nostri server non possono accedervi. Dovresti prima spostare quei video in una playlist pubblica o non elencata.",
    'If the live stream has ended and is available as a VOD, it will download normally. If the stream is currently live, the tool will skip it, as it has no finite length.': 'Se il live stream è terminato ed è disponibile come VOD, verrà scaricato normalmente. Se lo stream è attualmente live, lo strumento lo salterà, poiché non ha una lunghezza finita.',
    'Parsing the list takes only seconds. The conversion time depends on the total length of the videos and the chosen quality, but our concurrent processing usually finishes a typical music playlist in under 3 minutes.': 'L\'analisi dell\'elenco richiede solo pochi secondi. Il tempo di conversione dipende dalla lunghezza totale dei video e dalla qualità scelta, ma la nostra elaborazione concorrente di solito termina una tipica playlist musicale in meno di 3 minuti.',
    'Currently, browser security restrictions prevent websites from automatically triggering 50 file downloads at once. You will need to click the download button for each generated file.': 'Attualmente, le restrizioni di sicurezza del browser impediscono ai siti Web di attivare automaticamente 50 download di file contemporaneamente. Dovrai fare clic sul pulsante di download per ogni file generato.',
    'The individual video files will have their respective video thumbnails embedded as metadata (for audio formats) or as the poster frame (for video formats).': 'I singoli file video avranno le rispettive miniature video incorporate come metadati (per i formati audio) o come frame poster (per i formati video).',
    "If the channel has a 'Play All' button or a playlist containing all their uploads, yes. Just copy that specific playlist URL.": "Se il canale ha un pulsante 'Riproduci tutto' o una playlist contenente tutti i loro caricamenti, sì. Copia semplicemente quell'URL di playlist specifico.",
    "The files retain their original YouTube titles. If the creator numbered the titles (e.g., 'Episode 1: ...'), that numbering will be in your downloaded file.": "I file mantengono i loro titoli YouTube originali. Se il creatore ha numerato i titoli (ad es., 'Episodio 1: ...'), quella numerazione sarà nel tuo file scaricato.",
    'This usually means the missing videos are either Private, Deleted, or Region-Blocked. Our tool can only fetch publicly accessible media.': 'Questo di solito significa che i video mancanti sono privati, eliminati o bloccati per regione. Il nostro strumento può recuperare solo media accessibili pubblicamente.',
    'Bulk-convert every video in a playlist': 'Converti in blocco ogni video in una playlist',
    'Paste any public YouTube playlist URL (for example ?list=PL…) and yt2mp3.lol queues every video individually. Each conversion runs in parallel where possible, so even long playlists finish quickly. You get one clean file per video, named with the original title.': 'Incolla qualsiasi URL di playlist YouTube pubblica (ad esempio ?list=PL…) e yt2mp3.lol mette in coda ogni video individualmente. Ogni conversione viene eseguita in parallelo dove possibile, quindi anche le playlist lunghe finiscono rapidamente. Ottieni un file pulito per video, denominato con il titolo originale.',
    'Supports mixes and topic playlists': 'Supporta mix e playlist tematiche',
    'Auto-generated mixes, Topic artist playlists, and user-curated playlists all work as long as they\'re set to Public or Unlisted. Private playlists won\'t resolve.': 'I mix generati automaticamente, le playlist di artisti tematici e le playlist curate dagli utenti funzionano tutti purché siano impostati su Pubblico o Non elencato. Le playlist private non verranno risolte.',
    'Picking the right format': 'Scegliere il formato giusto',
    'For music, MP3 at 320 kbps is the standard. For podcasts, M4A produces smaller files at equal quality. For lecture series you plan to re-watch, MP4 at 720p balances storage and clarity.': 'Per la musica, MP3 a 320 kbps è lo standard. Per i podcast, M4A produce file più piccoli a parità di qualità. Per le serie di lezioni che prevedi di riguardare, MP4 a 720p bilancia archiviazione e chiarezza.',
    'Format Comparison Table': 'Tabella di confronto dei formati',
    'YouTube Shorts Downloader': 'Scaricatore YouTube Shorts', 'Download YouTube Shorts videos in MP3 or MP4 format. Fast, free, and easy to use.': 'Scarica video YouTube Shorts in formato MP3 o MP4. Veloce, gratuito e facile da usare.',
    'youtube shorts downloader, shorts to mp3, download youtube shorts, shorts converter': 'scaricatore youtube shorts, shorts in mp3, scarica youtube shorts, convertitore shorts',
    'YouTube Multi Downloader': 'Scaricatore multiplo YouTube', 'Download multiple YouTube videos at once. Paste multiple URLs and convert them all in one go.': 'Scarica più video YouTube contemporaneamente. Incolla più URL e convertili tutti in una volta.',
    'youtube multi downloader, bulk youtube download, multiple youtube videos, batch download': 'scaricatore multiplo youtube, download in blocco youtube, più video youtube, download batch',
}

def t(f):
    c = Path(f).read_text(encoding='utf-8')
    for e, b in italian.items(): c = c.replace(e, b)
    Path(f).write_text(c, encoding='utf-8')
    print(f"✓ {f}")

t('web/it/youtube-playlist-downloader/index.html')
t('web/it/youtube-shorts-downloader/index.html')
t('web/it/youtube-multi-downloader/index.html')
print("\n✅ Italian (it) complete - 3/3")
