#!/usr/bin/env python3
from pathlib import Path

spanish = {
    'Format': 'Formato', 'Best For': 'Mejor para', 'Quality Options': 'Opciones de calidad', 'File Size': 'Tamaño de archivo',
    'Universal audio playback': 'Reproducción de audio universal', 'Small': 'Pequeño', 'Video playback everywhere': 'Reproducción de video en todas partes',
    'Large': 'Grande', 'Lossless audio editing': 'Edición de audio sin pérdidas', 'Very Large': 'Muy grande', 'Apple devices': 'Dispositivos Apple',
    'Native AAC': 'AAC nativo', 'Medium': 'Mediano', 'Batch Conversion Masterclass': 'Clase magistral de conversión por lotes',
    'Preserve Original Order and Titles': 'Preservar orden y títulos originales', 'Flexible Format Selection for Playlists': 'Selección de formato flexible para listas de reproducción',
    'High-Concurrency Processing': 'Procesamiento de alta concurrencia', 'Support for Massive Playlists': 'Soporte para listas de reproducción masivas',
    'Download Auto-Generated Mixes': 'Descargar mezclas generadas automáticamente', 'Ideal for Educators and Students': 'Ideal para educadores y estudiantes',
    'Handling Unavailable or Private Videos': 'Manejo de videos no disponibles o privados', 'How to Download a Full Playlist': 'Cómo descargar una lista de reproducción completa',
    'Downloading videos one by one is incredibly tedious. Our YouTube Playlist Downloader is engineered for bulk operations. By parsing the playlist metadata, our servers generate individual conversion jobs for every single video in the list, allowing you to download an entire album, lecture series, or podcast backlog with minimal effort.': 'Descargar videos uno por uno es increíblemente tedioso. Nuestro descargador de listas de reproducción de YouTube está diseñado para operaciones masivas. Al analizar los metadatos de la lista de reproducción, nuestros servidores generan trabajos de conversión individuales para cada video en la lista, lo que le permite descargar un álbum completo, una serie de conferencias o un archivo de podcasts con un esfuerzo mínimo.',
    'When you download a playlist, organization is key. Our system automatically grabs the original video titles and structures the downloads so you can easily maintain the intended order. This is perfect for sequential tutorials, multi-part documentaries, or chronologically ordered music albums.': 'Cuando descarga una lista de reproducción, la organización es clave. Nuestro sistema captura automáticamente los títulos de video originales y estructura las descargas para que pueda mantener fácilmente el orden previsto. Esto es perfecto para tutoriales secuenciales, documentales de varias partes o álbumes de música ordenados cronológicamente.',
    "You aren't locked into a single format. You can choose to download an entire music playlist as crisp 320kbps MP3s, or an entire educational course as 1080p MP4s. Our FFmpeg backend applies your selected format uniformly across all items in the batch.": 'No está bloqueado en un solo formato. Puede elegir descargar una lista de reproducción de música completa como MP3 nítidos de 320kbps, o un curso educativo completo como MP4 de 1080p. Nuestro backend FFmpeg aplica su formato seleccionado uniformemente en todos los elementos del lote.',
    "We don't make you wait for one video to finish before starting the next. Our cloud infrastructure utilizes high-concurrency processing, meaning multiple videos from your playlist are downloaded and converted simultaneously. A 50-video playlist is processed significantly faster than doing it manually.": 'No le hacemos esperar a que termine un video antes de comenzar el siguiente. Nuestra infraestructura en la nube utiliza procesamiento de alta concurrencia, lo que significa que se descargan y convierten varios videos de su lista de reproducción simultáneamente. Una lista de reproducción de 50 videos se procesa significativamente más rápido que hacerlo manualmente.',
    "Whether it's a 10-track EP or a massive 300-video mega-mix, our tool is built to handle it. While extremely large playlists may take a few minutes to fully parse and render download buttons, our backend will not time out or crash during the operation.": 'Ya sea un EP de 10 pistas o una mega-mezcla masiva de 300 videos, nuestra herramienta está diseñada para manejarlo. Si bien las listas de reproducción extremadamente grandes pueden tardar unos minutos en analizarse completamente y renderizar los botones de descarga, nuestro backend no se agotará ni se bloqueará durante la operación.',
    "Did YouTube's algorithm create the perfect 'My Mix' or 'Discover Weekly' equivalent for you? Just copy the URL of that auto-generated playlist and paste it here. You can rip the entire curated mix to your local device for offline listening on road trips or flights.": "¿El algoritmo de YouTube creó el equivalente perfecto de 'Mi mezcla' o 'Descubrir semanalmente' para ti? Simplemente copia la URL de esa lista de reproducción generada automáticamente y pégala aquí. Puedes copiar toda la mezcla curada a tu dispositivo local para escuchar sin conexión en viajes por carretera o vuelos.",
    'Many professors and online instructors organize their course modules into public YouTube playlists. Students can use our tool to download the entire semester\'s worth of lectures in MP4 format, ensuring they have access to study materials even without an internet connection.': 'Muchos profesores e instructores en línea organizan sus módulos de curso en listas de reproducción públicas de YouTube. Los estudiantes pueden usar nuestra herramienta para descargar las conferencias de todo el semestre en formato MP4, asegurando que tengan acceso a materiales de estudio incluso sin conexión a Internet.',
    "Playlists often contain videos that have been deleted, made private, or restricted in your region. Our parser intelligently skips these dead links and continues processing the available videos, so your batch download isn't ruined by a single broken link.": 'Las listas de reproducción a menudo contienen videos que han sido eliminados, hechos privados o restringidos en su región. Nuestro analizador omite inteligentemente estos enlaces muertos y continúa procesando los videos disponibles, por lo que su descarga por lotes no se arruina por un solo enlace roto.',
    "1. Navigate to the playlist on YouTube. Ensure the URL contains 'list=' (e.g., youtube.com/playlist?list=...). 2. Copy the URL. 3. Paste it into our converter. 4. Select your global format (MP3 or MP4). 5. Click Convert. 6. Wait for the parser to extract the videos, then click the individual download buttons as they appear.": "1. Navegue a la lista de reproducción en YouTube. Asegúrese de que la URL contenga 'list=' (por ejemplo, youtube.com/playlist?list=...). 2. Copie la URL. 3. Péguela en nuestro convertidor. 4. Seleccione su formato global (MP3 o MP4). 5. Haga clic en Convertir. 6. Espere a que el analizador extraiga los videos, luego haga clic en los botones de descarga individuales a medida que aparecen.",
    'Is there a maximum playlist length?': '¿Hay una longitud máxima de lista de reproducción?', 'Are playlists downloaded in order?': '¿Las listas de reproducción se descargan en orden?',
    'Is there a limit to the number of videos in a playlist?': '¿Hay un límite en el número de videos en una lista de reproducción?', 'Will it download as one giant file or separate files?': '¿Se descargará como un archivo gigante o archivos separados?',
    "Can I download a 'Watch Later' playlist?": "¿Puedo descargar una lista de reproducción 'Ver más tarde'?", 'What happens if the playlist contains a live stream?': '¿Qué sucede si la lista de reproducción contiene una transmisión en vivo?',
    'How long does a 50-video playlist take to convert?': '¿Cuánto tiempo tarda en convertirse una lista de reproducción de 50 videos?', 'Do I have to click download 50 times?': '¿Tengo que hacer clic en descargar 50 veces?',
    'Does it download the playlist thumbnail?': '¿Descarga la miniatura de la lista de reproducción?', "Can I download a channel's entire video list?": '¿Puedo descargar la lista completa de videos de un canal?',
    'Are the files numbered?': '¿Los archivos están numerados?', 'Why did only half the videos appear?': '¿Por qué solo apareció la mitad de los videos?',
    'No hard cap, but very large playlists (500+ videos) may take several minutes to process in full.': 'No hay límite estricto, pero las listas de reproducción muy grandes (más de 500 videos) pueden tardar varios minutos en procesarse por completo.',
    'Yes. Original playlist ordering is preserved by default.': 'Sí. El orden original de la lista de reproducción se conserva de forma predeterminada.',
    'We can theoretically parse playlists of any size, but for optimal performance and browser stability, we recommend downloading playlists with 200 videos or fewer at a time.': 'Teóricamente podemos analizar listas de reproducción de cualquier tamaño, pero para un rendimiento óptimo y estabilidad del navegador, recomendamos descargar listas de reproducción con 200 videos o menos a la vez.',
    'Each video in the playlist is converted and downloaded as its own separate file. We do not merge them into a single massive audio/video file.': 'Cada video en la lista de reproducción se convierte y descarga como su propio archivo separado. No los fusionamos en un solo archivo de audio/video masivo.',
    "Your 'Watch Later' playlist is private to your account. Our servers cannot access it. You would need to move those videos to a Public or Unlisted playlist first.": "Su lista de reproducción 'Ver más tarde' es privada para su cuenta. Nuestros servidores no pueden acceder a ella. Primero tendría que mover esos videos a una lista de reproducción pública o no listada.",
    'If the live stream has ended and is available as a VOD, it will download normally. If the stream is currently live, the tool will skip it, as it has no finite length.': 'Si la transmisión en vivo ha terminado y está disponible como VOD, se descargará normalmente. Si la transmisión está actualmente en vivo, la herramienta la omitirá, ya que no tiene una longitud finita.',
    'Parsing the list takes only seconds. The conversion time depends on the total length of the videos and the chosen quality, but our concurrent processing usually finishes a typical music playlist in under 3 minutes.': 'Analizar la lista solo toma segundos. El tiempo de conversión depende de la longitud total de los videos y la calidad elegida, pero nuestro procesamiento concurrente generalmente termina una lista de reproducción de música típica en menos de 3 minutos.',
    'Currently, browser security restrictions prevent websites from automatically triggering 50 file downloads at once. You will need to click the download button for each generated file.': 'Actualmente, las restricciones de seguridad del navegador impiden que los sitios web activen automáticamente 50 descargas de archivos a la vez. Deberá hacer clic en el botón de descarga para cada archivo generado.',
    'The individual video files will have their respective video thumbnails embedded as metadata (for audio formats) or as the poster frame (for video formats).': 'Los archivos de video individuales tendrán sus respectivas miniaturas de video incrustadas como metadatos (para formatos de audio) o como marco de póster (para formatos de video).',
    "If the channel has a 'Play All' button or a playlist containing all their uploads, yes. Just copy that specific playlist URL.": "Si el canal tiene un botón 'Reproducir todo' o una lista de reproducción que contiene todas sus cargas, sí. Simplemente copie esa URL de lista de reproducción específica.",
    "The files retain their original YouTube titles. If the creator numbered the titles (e.g., 'Episode 1: ...'), that numbering will be in your downloaded file.": "Los archivos conservan sus títulos originales de YouTube. Si el creador numeró los títulos (por ejemplo, 'Episodio 1: ...'), esa numeración estará en su archivo descargado.",
    'This usually means the missing videos are either Private, Deleted, or Region-Blocked. Our tool can only fetch publicly accessible media.': 'Esto generalmente significa que los videos faltantes son privados, eliminados o bloqueados por región. Nuestra herramienta solo puede obtener medios de acceso público.',
    'Bulk-convert every video in a playlist': 'Convertir en masa cada video en una lista de reproducción',
    'Paste any public YouTube playlist URL (for example ?list=PL…) and yt2mp3.lol queues every video individually. Each conversion runs in parallel where possible, so even long playlists finish quickly. You get one clean file per video, named with the original title.': 'Pegue cualquier URL de lista de reproducción pública de YouTube (por ejemplo ?list=PL…) y yt2mp3.lol pone en cola cada video individualmente. Cada conversión se ejecuta en paralelo cuando es posible, por lo que incluso las listas de reproducción largas terminan rápidamente. Obtiene un archivo limpio por video, nombrado con el título original.',
    'Supports mixes and topic playlists': 'Admite mezclas y listas de reproducción de temas',
    'Auto-generated mixes, Topic artist playlists, and user-curated playlists all work as long as they\'re set to Public or Unlisted. Private playlists won\'t resolve.': 'Las mezclas generadas automáticamente, las listas de reproducción de artistas de temas y las listas de reproducción curadas por el usuario funcionan siempre que estén configuradas como públicas o no listadas. Las listas de reproducción privadas no se resolverán.',
    'Picking the right format': 'Elegir el formato correcto',
    'For music, MP3 at 320 kbps is the standard. For podcasts, M4A produces smaller files at equal quality. For lecture series you plan to re-watch, MP4 at 720p balances storage and clarity.': 'Para música, MP3 a 320 kbps es el estándar. Para podcasts, M4A produce archivos más pequeños con igual calidad. Para series de conferencias que planea volver a ver, MP4 a 720p equilibra almacenamiento y claridad.',
    'Format Comparison Table': 'Tabla de comparación de formatos',
    'YouTube Shorts Downloader': 'Descargador de YouTube Shorts', 'Download YouTube Shorts videos in MP3 or MP4 format. Fast, free, and easy to use.': 'Descargue videos de YouTube Shorts en formato MP3 o MP4. Rápido, gratis y fácil de usar.',
    'youtube shorts downloader, shorts to mp3, download youtube shorts, shorts converter': 'descargador de youtube shorts, shorts a mp3, descargar youtube shorts, convertidor de shorts',
    'YouTube Multi Downloader': 'Descargador múltiple de YouTube', 'Download multiple YouTube videos at once. Paste multiple URLs and convert them all in one go.': 'Descargue varios videos de YouTube a la vez. Pegue varias URL y conviértalas todas de una vez.',
    'youtube multi downloader, bulk youtube download, multiple youtube videos, batch download': 'descargador múltiple de youtube, descarga masiva de youtube, múltiples videos de youtube, descarga por lotes',
}

def t(f):
    c = Path(f).read_text(encoding='utf-8')
    for e, b in spanish.items(): c = c.replace(e, b)
    Path(f).write_text(c, encoding='utf-8')
    print(f"✓ {f}")

t('web/es/youtube-playlist-downloader/index.html')
t('web/es/youtube-shorts-downloader/index.html')
t('web/es/youtube-multi-downloader/index.html')
print("\n✅ Spanish (es) complete - 3/3")
