#!/usr/bin/env python3
from pathlib import Path

german = {
    'Format': 'Format', 'Best For': 'Am besten für', 'Quality Options': 'Qualitätsoptionen', 'File Size': 'Dateigröße',
    'Universal audio playback': 'Universelle Audio-Wiedergabe', 'Small': 'Klein', 'Video playback everywhere': 'Video-Wiedergabe überall',
    'Large': 'Groß', 'Lossless audio editing': 'Verlustfreie Audio-Bearbeitung', 'Very Large': 'Sehr groß', 'Apple devices': 'Apple-Geräte',
    'Native AAC': 'Natives AAC', 'Medium': 'Mittel', 'Batch Conversion Masterclass': 'Batch-Konvertierung Meisterklasse',
    'Preserve Original Order and Titles': 'Ursprüngliche Reihenfolge und Titel beibehalten', 'Flexible Format Selection for Playlists': 'Flexible Formatauswahl für Playlists',
    'High-Concurrency Processing': 'Hochparallele Verarbeitung', 'Support for Massive Playlists': 'Unterstützung für massive Playlists',
    'Download Auto-Generated Mixes': 'Automatisch generierte Mixe herunterladen', 'Ideal for Educators and Students': 'Ideal für Pädagogen und Studenten',
    'Handling Unavailable or Private Videos': 'Umgang mit nicht verfügbaren oder privaten Videos', 'How to Download a Full Playlist': 'So laden Sie eine vollständige Playlist herunter',
    'Downloading videos one by one is incredibly tedious. Our YouTube Playlist Downloader is engineered for bulk operations. By parsing the playlist metadata, our servers generate individual conversion jobs for every single video in the list, allowing you to download an entire album, lecture series, or podcast backlog with minimal effort.': 'Das Herunterladen von Videos einzeln ist unglaublich mühsam. Unser YouTube Playlist Downloader ist für Massenoperationen entwickelt. Durch das Parsen der Playlist-Metadaten generieren unsere Server individuelle Konvertierungsaufträge für jedes einzelne Video in der Liste, sodass Sie mit minimalem Aufwand ein ganzes Album, eine Vorlesungsreihe oder einen Podcast-Rückstand herunterladen können.',
    'When you download a playlist, organization is key. Our system automatically grabs the original video titles and structures the downloads so you can easily maintain the intended order. This is perfect for sequential tutorials, multi-part documentaries, or chronologically ordered music albums.': 'Wenn Sie eine Playlist herunterladen, ist Organisation der Schlüssel. Unser System erfasst automatisch die ursprünglichen Videotitel und strukturiert die Downloads, sodass Sie die beabsichtigte Reihenfolge leicht beibehalten können. Dies ist perfekt für sequenzielle Tutorials, mehrteilige Dokumentationen oder chronologisch geordnete Musikalben.',
    "You aren't locked into a single format. You can choose to download an entire music playlist as crisp 320kbps MP3s, or an entire educational course as 1080p MP4s. Our FFmpeg backend applies your selected format uniformly across all items in the batch.": 'Sie sind nicht auf ein einziges Format festgelegt. Sie können wählen, eine gesamte Musik-Playlist als knackige 320kbps MP3s herunterzuladen oder einen gesamten Bildungskurs als 1080p MP4s. Unser FFmpeg-Backend wendet Ihr ausgewähltes Format einheitlich auf alle Elemente im Batch an.',
    "We don't make you wait for one video to finish before starting the next. Our cloud infrastructure utilizes high-concurrency processing, meaning multiple videos from your playlist are downloaded and converted simultaneously. A 50-video playlist is processed significantly faster than doing it manually.": 'Wir lassen Sie nicht warten, bis ein Video fertig ist, bevor das nächste beginnt. Unsere Cloud-Infrastruktur nutzt hochparallele Verarbeitung, was bedeutet, dass mehrere Videos aus Ihrer Playlist gleichzeitig heruntergeladen und konvertiert werden. Eine 50-Video-Playlist wird deutlich schneller verarbeitet als manuell.',
    "Whether it's a 10-track EP or a massive 300-video mega-mix, our tool is built to handle it. While extremely large playlists may take a few minutes to fully parse and render download buttons, our backend will not time out or crash during the operation.": 'Ob es sich um eine 10-Track-EP oder einen massiven 300-Video-Mega-Mix handelt, unser Tool ist dafür gebaut. Während extrem große Playlists einige Minuten zum vollständigen Parsen und Rendern von Download-Buttons benötigen können, wird unser Backend während des Vorgangs nicht auslaufen oder abstürzen.',
    "Did YouTube's algorithm create the perfect 'My Mix' or 'Discover Weekly' equivalent for you? Just copy the URL of that auto-generated playlist and paste it here. You can rip the entire curated mix to your local device for offline listening on road trips or flights.": "Hat YouTubes Algorithmus das perfekte 'My Mix' oder 'Discover Weekly'-Äquivalent für Sie erstellt? Kopieren Sie einfach die URL dieser automatisch generierten Playlist und fügen Sie sie hier ein. Sie können den gesamten kuratierten Mix auf Ihr lokales Gerät rippen, um ihn offline auf Roadtrips oder Flügen zu hören.",
    'Many professors and online instructors organize their course modules into public YouTube playlists. Students can use our tool to download the entire semester\'s worth of lectures in MP4 format, ensuring they have access to study materials even without an internet connection.': 'Viele Professoren und Online-Dozenten organisieren ihre Kursmodule in öffentlichen YouTube-Playlists. Studenten können unser Tool verwenden, um die Vorlesungen eines ganzen Semesters im MP4-Format herunterzuladen und so sicherzustellen, dass sie auch ohne Internetverbindung Zugang zu Lernmaterialien haben.',
    "Playlists often contain videos that have been deleted, made private, or restricted in your region. Our parser intelligently skips these dead links and continues processing the available videos, so your batch download isn't ruined by a single broken link.": 'Playlists enthalten oft Videos, die gelöscht, privat gemacht oder in Ihrer Region eingeschränkt wurden. Unser Parser überspringt diese toten Links intelligent und verarbeitet die verfügbaren Videos weiter, sodass Ihr Batch-Download nicht durch einen einzigen defekten Link ruiniert wird.',
    "1. Navigate to the playlist on YouTube. Ensure the URL contains 'list=' (e.g., youtube.com/playlist?list=...). 2. Copy the URL. 3. Paste it into our converter. 4. Select your global format (MP3 or MP4). 5. Click Convert. 6. Wait for the parser to extract the videos, then click the individual download buttons as they appear.": "1. Navigieren Sie zur Playlist auf YouTube. Stellen Sie sicher, dass die URL 'list=' enthält (z.B. youtube.com/playlist?list=...). 2. Kopieren Sie die URL. 3. Fügen Sie sie in unseren Konverter ein. 4. Wählen Sie Ihr globales Format (MP3 oder MP4). 5. Klicken Sie auf Konvertieren. 6. Warten Sie, bis der Parser die Videos extrahiert, und klicken Sie dann auf die einzelnen Download-Buttons, sobald sie erscheinen.",
    'Is there a maximum playlist length?': 'Gibt es eine maximale Playlist-Länge?', 'Are playlists downloaded in order?': 'Werden Playlists in Reihenfolge heruntergeladen?',
    'Is there a limit to the number of videos in a playlist?': 'Gibt es eine Begrenzung für die Anzahl der Videos in einer Playlist?', 'Will it download as one giant file or separate files?': 'Wird es als eine riesige Datei oder als separate Dateien heruntergeladen?',
    "Can I download a 'Watch Later' playlist?": "Kann ich eine 'Später ansehen'-Playlist herunterladen?", 'What happens if the playlist contains a live stream?': 'Was passiert, wenn die Playlist einen Livestream enthält?',
    'How long does a 50-video playlist take to convert?': 'Wie lange dauert die Konvertierung einer 50-Video-Playlist?', 'Do I have to click download 50 times?': 'Muss ich 50 Mal auf Download klicken?',
    'Does it download the playlist thumbnail?': 'Lädt es das Playlist-Thumbnail herunter?', "Can I download a channel's entire video list?": 'Kann ich die gesamte Videoliste eines Kanals herunterladen?',
    'Are the files numbered?': 'Sind die Dateien nummeriert?', 'Why did only half the videos appear?': 'Warum sind nur die Hälfte der Videos erschienen?',
    'No hard cap, but very large playlists (500+ videos) may take several minutes to process in full.': 'Keine harte Obergrenze, aber sehr große Playlists (500+ Videos) können mehrere Minuten zur vollständigen Verarbeitung benötigen.',
    'Yes. Original playlist ordering is preserved by default.': 'Ja. Die ursprüngliche Playlist-Reihenfolge wird standardmäßig beibehalten.',
    'We can theoretically parse playlists of any size, but for optimal performance and browser stability, we recommend downloading playlists with 200 videos or fewer at a time.': 'Wir können theoretisch Playlists jeder Größe parsen, aber für optimale Leistung und Browser-Stabilität empfehlen wir, Playlists mit 200 oder weniger Videos gleichzeitig herunterzuladen.',
    'Each video in the playlist is converted and downloaded as its own separate file. We do not merge them into a single massive audio/video file.': 'Jedes Video in der Playlist wird als eigene separate Datei konvertiert und heruntergeladen. Wir fügen sie nicht zu einer einzigen massiven Audio-/Videodatei zusammen.',
    "Your 'Watch Later' playlist is private to your account. Our servers cannot access it. You would need to move those videos to a Public or Unlisted playlist first.": "Ihre 'Später ansehen'-Playlist ist privat für Ihr Konto. Unsere Server können nicht darauf zugreifen. Sie müssten diese Videos zuerst in eine öffentliche oder nicht gelistete Playlist verschieben.",
    'If the live stream has ended and is available as a VOD, it will download normally. If the stream is currently live, the tool will skip it, as it has no finite length.': 'Wenn der Livestream beendet ist und als VOD verfügbar ist, wird er normal heruntergeladen. Wenn der Stream derzeit live ist, überspringt das Tool ihn, da er keine endliche Länge hat.',
    'Parsing the list takes only seconds. The conversion time depends on the total length of the videos and the chosen quality, but our concurrent processing usually finishes a typical music playlist in under 3 minutes.': 'Das Parsen der Liste dauert nur Sekunden. Die Konvertierungszeit hängt von der Gesamtlänge der Videos und der gewählten Qualität ab, aber unsere parallele Verarbeitung beendet normalerweise eine typische Musik-Playlist in unter 3 Minuten.',
    'Currently, browser security restrictions prevent websites from automatically triggering 50 file downloads at once. You will need to click the download button for each generated file.': 'Derzeit verhindern Browser-Sicherheitsbeschränkungen, dass Websites automatisch 50 Datei-Downloads auf einmal auslösen. Sie müssen für jede generierte Datei auf die Download-Schaltfläche klicken.',
    'The individual video files will have their respective video thumbnails embedded as metadata (for audio formats) or as the poster frame (for video formats).': 'Die einzelnen Videodateien haben ihre jeweiligen Video-Thumbnails als Metadaten eingebettet (für Audioformate) oder als Poster-Frame (für Videoformate).',
    "If the channel has a 'Play All' button or a playlist containing all their uploads, yes. Just copy that specific playlist URL.": "Wenn der Kanal eine 'Alle abspielen'-Schaltfläche oder eine Playlist mit allen Uploads hat, ja. Kopieren Sie einfach diese spezifische Playlist-URL.",
    "The files retain their original YouTube titles. If the creator numbered the titles (e.g., 'Episode 1: ...'), that numbering will be in your downloaded file.": "Die Dateien behalten ihre ursprünglichen YouTube-Titel. Wenn der Ersteller die Titel nummeriert hat (z.B. 'Episode 1: ...'), wird diese Nummerierung in Ihrer heruntergeladenen Datei sein.",
    'This usually means the missing videos are either Private, Deleted, or Region-Blocked. Our tool can only fetch publicly accessible media.': 'Dies bedeutet normalerweise, dass die fehlenden Videos entweder privat, gelöscht oder regional gesperrt sind. Unser Tool kann nur öffentlich zugängliche Medien abrufen.',
    'Bulk-convert every video in a playlist': 'Massenkonvertierung jedes Videos in einer Playlist',
    'Paste any public YouTube playlist URL (for example ?list=PL…) and yt2mp3.lol queues every video individually. Each conversion runs in parallel where possible, so even long playlists finish quickly. You get one clean file per video, named with the original title.': 'Fügen Sie eine beliebige öffentliche YouTube-Playlist-URL ein (z.B. ?list=PL…) und yt2mp3.lol stellt jedes Video einzeln in die Warteschlange. Jede Konvertierung läuft parallel, wo möglich, sodass selbst lange Playlists schnell fertig werden. Sie erhalten eine saubere Datei pro Video, benannt mit dem Originaltitel.',
    'Supports mixes and topic playlists': 'Unterstützt Mixe und Themen-Playlists',
    'Auto-generated mixes, Topic artist playlists, and user-curated playlists all work as long as they\'re set to Public or Unlisted. Private playlists won\'t resolve.': 'Automatisch generierte Mixe, Themen-Künstler-Playlists und benutzerkuratierte Playlists funktionieren alle, solange sie auf Öffentlich oder Nicht gelistet eingestellt sind. Private Playlists werden nicht aufgelöst.',
    'Picking the right format': 'Das richtige Format wählen',
    'For music, MP3 at 320 kbps is the standard. For podcasts, M4A produces smaller files at equal quality. For lecture series you plan to re-watch, MP4 at 720p balances storage and clarity.': 'Für Musik ist MP3 mit 320 kbps der Standard. Für Podcasts erzeugt M4A kleinere Dateien bei gleicher Qualität. Für Vorlesungsreihen, die Sie erneut ansehen möchten, balanciert MP4 mit 720p Speicher und Klarheit.',
    'Format Comparison Table': 'Format-Vergleichstabelle',
    'YouTube Shorts Downloader': 'YouTube Shorts Downloader', 'Download YouTube Shorts videos in MP3 or MP4 format. Fast, free, and easy to use.': 'Laden Sie YouTube Shorts-Videos im MP3- oder MP4-Format herunter. Schnell, kostenlos und einfach zu bedienen.',
    'youtube shorts downloader, shorts to mp3, download youtube shorts, shorts converter': 'youtube shorts downloader, shorts zu mp3, youtube shorts herunterladen, shorts konverter',
    'YouTube Multi Downloader': 'YouTube Multi Downloader', 'Download multiple YouTube videos at once. Paste multiple URLs and convert them all in one go.': 'Laden Sie mehrere YouTube-Videos auf einmal herunter. Fügen Sie mehrere URLs ein und konvertieren Sie sie alle auf einmal.',
    'youtube multi downloader, bulk youtube download, multiple youtube videos, batch download': 'youtube multi downloader, bulk youtube download, mehrere youtube videos, batch download',
}

def t(f):
    c = Path(f).read_text(encoding='utf-8')
    for e, b in german.items(): c = c.replace(e, b)
    Path(f).write_text(c, encoding='utf-8')
    print(f"✓ {f}")

t('web/de/youtube-playlist-downloader/index.html')
t('web/de/youtube-shorts-downloader/index.html')
t('web/de/youtube-multi-downloader/index.html')
print("\n✅ German (de) complete - 3/3")
