#!/usr/bin/env python3
from pathlib import Path

filipino = {
    'Format': 'Format', 'Best For': 'Pinakamahusay Para sa', 'Quality Options': 'Mga Opsyon sa Kalidad', 'File Size': 'Laki ng File',
    'Universal audio playback': 'Unibersal na audio playback', 'Small': 'Maliit', 'Video playback everywhere': 'Video playback kahit saan',
    'Large': 'Malaki', 'Lossless audio editing': 'Walang pagkalugi na audio editing', 'Very Large': 'Napakaki', 'Apple devices': 'Mga Apple device',
    'Native AAC': 'Native AAC', 'Medium': 'Katamtaman', 'Batch Conversion Masterclass': 'Batch Conversion Masterclass',
    'Preserve Original Order and Titles': 'Panatilihin ang Orihinal na Pagkakasunod-sunod at Mga Pamagat', 'Flexible Format Selection for Playlists': 'Flexible na Pagpili ng Format para sa Mga Playlist',
    'High-Concurrency Processing': 'Mataas na Concurrency Processing', 'Support for Massive Playlists': 'Suporta para sa Malalaking Playlist',
    'Download Auto-Generated Mixes': 'I-download ang Auto-Generated na Mga Mix', 'Ideal for Educators and Students': 'Perpekto para sa mga Guro at Estudyante',
    'Handling Unavailable or Private Videos': 'Paghawak ng Hindi Available o Private na Mga Video', 'How to Download a Full Playlist': 'Paano Mag-download ng Buong Playlist',
    'Downloading videos one by one is incredibly tedious. Our YouTube Playlist Downloader is engineered for bulk operations. By parsing the playlist metadata, our servers generate individual conversion jobs for every single video in the list, allowing you to download an entire album, lecture series, or podcast backlog with minimal effort.': 'Ang pag-download ng mga video isa-isa ay napakahirap. Ang aming YouTube Playlist Downloader ay dinisenyo para sa bulk operations. Sa pamamagitan ng pag-parse ng playlist metadata, ang aming mga server ay bumubuo ng indibidwal na conversion jobs para sa bawat video sa listahan, na nagpapahintulot sa iyo na mag-download ng buong album, lecture series, o podcast backlog nang may kaunting pagsisikap.',
    'When you download a playlist, organization is key. Our system automatically grabs the original video titles and structures the downloads so you can easily maintain the intended order. This is perfect for sequential tutorials, multi-part documentaries, or chronologically ordered music albums.': 'Kapag nag-download ka ng playlist, ang organisasyon ay susi. Ang aming sistema ay awtomatikong kumukuha ng mga orihinal na pamagat ng video at nag-istruktura ng mga download upang madali mong mapanatili ang nilalayong pagkakasunod-sunod. Ito ay perpekto para sa sequential na mga tutorial, multi-part na mga dokumentaryo, o chronologically ordered na mga music album.',
    "You aren't locked into a single format. You can choose to download an entire music playlist as crisp 320kbps MP3s, or an entire educational course as 1080p MP4s. Our FFmpeg backend applies your selected format uniformly across all items in the batch.": 'Hindi ka nakakulong sa isang format. Maaari mong piliin na i-download ang buong music playlist bilang crisp 320kbps MP3s, o isang buong educational course bilang 1080p MP4s. Ang aming FFmpeg backend ay nag-aaply ng iyong napiling format nang pantay-pantay sa lahat ng mga item sa batch.',
    "We don't make you wait for one video to finish before starting the next. Our cloud infrastructure utilizes high-concurrency processing, meaning multiple videos from your playlist are downloaded and converted simultaneously. A 50-video playlist is processed significantly faster than doing it manually.": 'Hindi ka namin pinapaghintay na matapos ang isang video bago magsimula ang susunod. Ang aming cloud infrastructure ay gumagamit ng high-concurrency processing, ibig sabihin ay maraming video mula sa iyong playlist ang dina-download at kino-convert nang sabay-sabay. Ang 50-video playlist ay napoproseso nang mas mabilis kaysa sa manu-manong paggawa nito.',
    "Whether it's a 10-track EP or a massive 300-video mega-mix, our tool is built to handle it. While extremely large playlists may take a few minutes to fully parse and render download buttons, our backend will not time out or crash during the operation.": 'Maging 10-track EP man o malaking 300-video mega-mix, ang aming tool ay binuo upang hawakan ito. Habang ang napakalalaking mga playlist ay maaaring tumagal ng ilang minuto upang ganap na ma-parse at ma-render ang mga download button, ang aming backend ay hindi mag-time out o mag-crash sa panahon ng operasyon.',
    "Did YouTube's algorithm create the perfect 'My Mix' or 'Discover Weekly' equivalent for you? Just copy the URL of that auto-generated playlist and paste it here. You can rip the entire curated mix to your local device for offline listening on road trips or flights.": "Gumawa ba ang algorithm ng YouTube ng perpektong 'My Mix' o 'Discover Weekly' equivalent para sa iyo? Kopyahin lang ang URL ng auto-generated na playlist na iyon at i-paste dito. Maaari mong i-rip ang buong curated mix sa iyong lokal na device para sa offline listening sa mga road trip o flight.",
    'Many professors and online instructors organize their course modules into public YouTube playlists. Students can use our tool to download the entire semester\'s worth of lectures in MP4 format, ensuring they have access to study materials even without an internet connection.': 'Maraming mga propesor at online instructor ang nag-oorganisa ng kanilang mga course module sa mga pampublikong YouTube playlist. Ang mga estudyante ay maaaring gumamit ng aming tool upang i-download ang buong semester na halaga ng mga lektura sa MP4 format, na nagsisiguro na mayroon silang access sa mga study material kahit walang internet connection.',
    "Playlists often contain videos that have been deleted, made private, or restricted in your region. Our parser intelligently skips these dead links and continues processing the available videos, so your batch download isn't ruined by a single broken link.": 'Ang mga playlist ay madalas na naglalaman ng mga video na na-delete, ginawang private, o restricted sa iyong rehiyon. Ang aming parser ay matalinong lumilipas sa mga patay na link at patuloy na nagpoproseso ng mga available na video, kaya ang iyong batch download ay hindi nasira ng isang sirang link.',
    "1. Navigate to the playlist on YouTube. Ensure the URL contains 'list=' (e.g., youtube.com/playlist?list=...). 2. Copy the URL. 3. Paste it into our converter. 4. Select your global format (MP3 or MP4). 5. Click Convert. 6. Wait for the parser to extract the videos, then click the individual download buttons as they appear.": "1. Mag-navigate sa playlist sa YouTube. Siguraduhing naglalaman ang URL ng 'list=' (hal., youtube.com/playlist?list=...). 2. Kopyahin ang URL. 3. I-paste ito sa aming converter. 4. Piliin ang iyong global format (MP3 o MP4). 5. I-click ang Convert. 6. Maghintay para sa parser na mag-extract ng mga video, pagkatapos ay i-click ang mga indibidwal na download button habang lumalabas ang mga ito.",
    'Is there a maximum playlist length?': 'May maximum playlist length ba?', 'Are playlists downloaded in order?': 'Ang mga playlist ba ay dina-download nang maayos?',
    'Is there a limit to the number of videos in a playlist?': 'May limitasyon ba sa bilang ng mga video sa isang playlist?', 'Will it download as one giant file or separate files?': 'Ito ba ay ida-download bilang isang malaking file o hiwalay na mga file?',
    "Can I download a 'Watch Later' playlist?": "Maaari ko bang i-download ang 'Watch Later' playlist?", 'What happens if the playlist contains a live stream?': 'Ano ang mangyayari kung ang playlist ay naglalaman ng live stream?',
    'How long does a 50-video playlist take to convert?': 'Gaano katagal ang pag-convert ng 50-video playlist?', 'Do I have to click download 50 times?': 'Kailangan ko bang mag-click ng download ng 50 beses?',
    'Does it download the playlist thumbnail?': 'Dina-download ba nito ang playlist thumbnail?', "Can I download a channel's entire video list?": 'Maaari ko bang i-download ang buong video list ng isang channel?',
    'Are the files numbered?': 'Ang mga file ba ay may numero?', 'Why did only half the videos appear?': 'Bakit kalahati lang ng mga video ang lumabas?',
    'No hard cap, but very large playlists (500+ videos) may take several minutes to process in full.': 'Walang hard cap, ngunit ang napakalalaking mga playlist (500+ video) ay maaaring tumagal ng ilang minuto upang ganap na maproseso.',
    'Yes. Original playlist ordering is preserved by default.': 'Oo. Ang orihinal na pagkakasunod-sunod ng playlist ay napapanatili bilang default.',
    'We can theoretically parse playlists of any size, but for optimal performance and browser stability, we recommend downloading playlists with 200 videos or fewer at a time.': 'Maaari kaming teoretikal na mag-parse ng mga playlist ng anumang laki, ngunit para sa optimal na performance at browser stability, inirerekomenda namin ang pag-download ng mga playlist na may 200 video o mas kaunti sa isang pagkakataon.',
    'Each video in the playlist is converted and downloaded as its own separate file. We do not merge them into a single massive audio/video file.': 'Ang bawat video sa playlist ay kino-convert at dina-download bilang sariling hiwalay na file. Hindi namin pinagsasama ang mga ito sa isang malaking audio/video file.',
    "Your 'Watch Later' playlist is private to your account. Our servers cannot access it. You would need to move those videos to a Public or Unlisted playlist first.": "Ang iyong 'Watch Later' playlist ay pribado sa iyong account. Ang aming mga server ay hindi maaaring mag-access nito. Kailangan mong ilipat muna ang mga video na iyon sa isang Pampubliko o Unlisted na playlist.",
    'If the live stream has ended and is available as a VOD, it will download normally. If the stream is currently live, the tool will skip it, as it has no finite length.': 'Kung ang live stream ay natapos na at available bilang VOD, ito ay ida-download nang normal. Kung ang stream ay kasalukuyang live, ang tool ay lalaktawan ito, dahil wala itong tiyak na haba.',
    'Parsing the list takes only seconds. The conversion time depends on the total length of the videos and the chosen quality, but our concurrent processing usually finishes a typical music playlist in under 3 minutes.': 'Ang pag-parse ng listahan ay tumatagal lamang ng ilang segundo. Ang oras ng conversion ay nakadepende sa kabuuang haba ng mga video at ang napiling kalidad, ngunit ang aming concurrent processing ay karaniwang nagtatapos ng isang tipikal na music playlist sa loob ng 3 minuto.',
    'Currently, browser security restrictions prevent websites from automatically triggering 50 file downloads at once. You will need to click the download button for each generated file.': 'Sa kasalukuyan, ang mga paghihigpit sa seguridad ng browser ay pumipigil sa mga website na awtomatikong mag-trigger ng 50 file download nang sabay-sabay. Kailangan mong i-click ang download button para sa bawat nabuong file.',
    'The individual video files will have their respective video thumbnails embedded as metadata (for audio formats) or as the poster frame (for video formats).': 'Ang mga indibidwal na video file ay magkakaroon ng kani-kanilang mga video thumbnail na naka-embed bilang metadata (para sa mga audio format) o bilang poster frame (para sa mga video format).',
    "If the channel has a 'Play All' button or a playlist containing all their uploads, yes. Just copy that specific playlist URL.": "Kung ang channel ay may 'Play All' button o isang playlist na naglalaman ng lahat ng kanilang mga upload, oo. Kopyahin lang ang partikular na playlist URL na iyon.",
    "The files retain their original YouTube titles. If the creator numbered the titles (e.g., 'Episode 1: ...'), that numbering will be in your downloaded file.": "Ang mga file ay napapanatili ang kanilang orihinal na mga pamagat sa YouTube. Kung ang creator ay nag-numero ng mga pamagat (hal., 'Episode 1: ...'), ang numerong iyon ay magiging nasa iyong na-download na file.",
    'This usually means the missing videos are either Private, Deleted, or Region-Blocked. Our tool can only fetch publicly accessible media.': 'Ito ay karaniwang nangangahulugan na ang mga nawawalang video ay alinman sa Private, Deleted, o Region-Blocked. Ang aming tool ay maaari lamang kumuha ng publicly accessible na media.',
    'Bulk-convert every video in a playlist': 'Bulk-convert ang bawat video sa isang playlist',
    'Paste any public YouTube playlist URL (for example ?list=PL…) and yt2mp3.lol queues every video individually. Each conversion runs in parallel where possible, so even long playlists finish quickly. You get one clean file per video, named with the original title.': 'I-paste ang anumang pampublikong YouTube playlist URL (halimbawa ?list=PL…) at ang yt2mp3.lol ay nag-queue ng bawat video nang indibidwal. Ang bawat conversion ay tumatakbo nang parallel kung saan posible, kaya kahit ang mahabang mga playlist ay matapos nang mabilis. Makakakuha ka ng isang malinis na file bawat video, na pinangalanan gamit ang orihinal na pamagat.',
    'Supports mixes and topic playlists': 'Sumusuporta sa mga mix at topic playlist',
    'Auto-generated mixes, Topic artist playlists, and user-curated playlists all work as long as they\'re set to Public or Unlisted. Private playlists won\'t resolve.': 'Ang mga auto-generated na mix, Topic artist playlist, at user-curated na mga playlist ay gumagana hangga\'t nakatakda ang mga ito sa Public o Unlisted. Ang mga pribadong playlist ay hindi mare-resolve.',
    'Picking the right format': 'Pagpili ng tamang format',
    'For music, MP3 at 320 kbps is the standard. For podcasts, M4A produces smaller files at equal quality. For lecture series you plan to re-watch, MP4 at 720p balances storage and clarity.': 'Para sa musika, ang MP3 sa 320 kbps ay ang pamantayan. Para sa mga podcast, ang M4A ay gumagawa ng mas maliit na mga file sa pantay na kalidad. Para sa mga lecture series na plano mong panoorin muli, ang MP4 sa 720p ay nagbabalanse ng storage at kalinawan.',
    'Format Comparison Table': 'Talahanayan ng Paghahambing ng Format',
    'YouTube Shorts Downloader': 'YouTube Shorts Downloader', 'Download YouTube Shorts videos in MP3 or MP4 format. Fast, free, and easy to use.': 'I-download ang mga YouTube Shorts video sa MP3 o MP4 format. Mabilis, libre, at madaling gamitin.',
    'youtube shorts downloader, shorts to mp3, download youtube shorts, shorts converter': 'youtube shorts downloader, shorts to mp3, download youtube shorts, shorts converter',
    'YouTube Multi Downloader': 'YouTube Multi Downloader', 'Download multiple YouTube videos at once. Paste multiple URLs and convert them all in one go.': 'I-download ang maraming YouTube video nang sabay-sabay. I-paste ang maraming URL at i-convert ang lahat nang sabay-sabay.',
    'youtube multi downloader, bulk youtube download, multiple youtube videos, batch download': 'youtube multi downloader, bulk youtube download, maraming youtube video, batch download',
}

def t(f):
    c = Path(f).read_text(encoding='utf-8')
    for e, b in filipino.items(): c = c.replace(e, b)
    Path(f).write_text(c, encoding='utf-8')
    print(f"✓ {f}")

t('web/fil/youtube-playlist-downloader/index.html')
t('web/fil/youtube-shorts-downloader/index.html')
t('web/fil/youtube-multi-downloader/index.html')
print("\n✅ Filipino (fil) complete - 3/3")
