#!/usr/bin/env python3
from pathlib import Path

french = {
    'Format': 'Format', 'Best For': 'Idéal pour', 'Quality Options': 'Options de qualité', 'File Size': 'Taille du fichier',
    'Universal audio playback': 'Lecture audio universelle', 'Small': 'Petit', 'Video playback everywhere': 'Lecture vidéo partout',
    'Large': 'Grand', 'Lossless audio editing': 'Édition audio sans perte', 'Very Large': 'Très grand', 'Apple devices': 'Appareils Apple',
    'Native AAC': 'AAC natif', 'Medium': 'Moyen', 'Batch Conversion Masterclass': 'Masterclass de conversion par lots',
    'Preserve Original Order and Titles': 'Préserver l\'ordre et les titres d\'origine', 'Flexible Format Selection for Playlists': 'Sélection de format flexible pour les playlists',
    'High-Concurrency Processing': 'Traitement à haute concurrence', 'Support for Massive Playlists': 'Support pour les playlists massives',
    'Download Auto-Generated Mixes': 'Télécharger les mix générés automatiquement', 'Ideal for Educators and Students': 'Idéal pour les éducateurs et les étudiants',
    'Handling Unavailable or Private Videos': 'Gestion des vidéos indisponibles ou privées', 'How to Download a Full Playlist': 'Comment télécharger une playlist complète',
    'Downloading videos one by one is incredibly tedious. Our YouTube Playlist Downloader is engineered for bulk operations. By parsing the playlist metadata, our servers generate individual conversion jobs for every single video in the list, allowing you to download an entire album, lecture series, or podcast backlog with minimal effort.': 'Télécharger des vidéos une par une est incroyablement fastidieux. Notre téléchargeur de playlist YouTube est conçu pour les opérations en masse. En analysant les métadonnées de la playlist, nos serveurs génèrent des tâches de conversion individuelles pour chaque vidéo de la liste, vous permettant de télécharger un album entier, une série de conférences ou un arriéré de podcasts avec un effort minimal.',
    'When you download a playlist, organization is key. Our system automatically grabs the original video titles and structures the downloads so you can easily maintain the intended order. This is perfect for sequential tutorials, multi-part documentaries, or chronologically ordered music albums.': 'Lorsque vous téléchargez une playlist, l\'organisation est essentielle. Notre système récupère automatiquement les titres vidéo d\'origine et structure les téléchargements afin que vous puissiez facilement maintenir l\'ordre prévu. C\'est parfait pour les tutoriels séquentiels, les documentaires en plusieurs parties ou les albums de musique classés chronologiquement.',
    "You aren't locked into a single format. You can choose to download an entire music playlist as crisp 320kbps MP3s, or an entire educational course as 1080p MP4s. Our FFmpeg backend applies your selected format uniformly across all items in the batch.": 'Vous n\'êtes pas verrouillé dans un seul format. Vous pouvez choisir de télécharger une playlist musicale entière en MP3 nets de 320 kbps, ou un cours éducatif entier en MP4 1080p. Notre backend FFmpeg applique votre format sélectionné uniformément sur tous les éléments du lot.',
    "We don't make you wait for one video to finish before starting the next. Our cloud infrastructure utilizes high-concurrency processing, meaning multiple videos from your playlist are downloaded and converted simultaneously. A 50-video playlist is processed significantly faster than doing it manually.": 'Nous ne vous faisons pas attendre qu\'une vidéo se termine avant de commencer la suivante. Notre infrastructure cloud utilise un traitement à haute concurrence, ce qui signifie que plusieurs vidéos de votre playlist sont téléchargées et converties simultanément. Une playlist de 50 vidéos est traitée beaucoup plus rapidement que manuellement.',
    "Whether it's a 10-track EP or a massive 300-video mega-mix, our tool is built to handle it. While extremely large playlists may take a few minutes to fully parse and render download buttons, our backend will not time out or crash during the operation.": 'Qu\'il s\'agisse d\'un EP de 10 pistes ou d\'un méga-mix massif de 300 vidéos, notre outil est conçu pour le gérer. Bien que les playlists extrêmement grandes puissent prendre quelques minutes pour être entièrement analysées et afficher les boutons de téléchargement, notre backend ne s\'arrêtera pas ou ne plantera pas pendant l\'opération.',
    "Did YouTube's algorithm create the perfect 'My Mix' or 'Discover Weekly' equivalent for you? Just copy the URL of that auto-generated playlist and paste it here. You can rip the entire curated mix to your local device for offline listening on road trips or flights.": "L'algorithme de YouTube a-t-il créé l'équivalent parfait de 'Mon Mix' ou 'Découvrir hebdomadaire' pour vous? Copiez simplement l'URL de cette playlist générée automatiquement et collez-la ici. Vous pouvez extraire l'intégralité du mix organisé sur votre appareil local pour une écoute hors ligne lors de voyages en voiture ou de vols.",
    'Many professors and online instructors organize their course modules into public YouTube playlists. Students can use our tool to download the entire semester\'s worth of lectures in MP4 format, ensuring they have access to study materials even without an internet connection.': 'De nombreux professeurs et instructeurs en ligne organisent leurs modules de cours dans des playlists YouTube publiques. Les étudiants peuvent utiliser notre outil pour télécharger les cours d\'un semestre entier au format MP4, garantissant qu\'ils ont accès aux supports d\'étude même sans connexion Internet.',
    "Playlists often contain videos that have been deleted, made private, or restricted in your region. Our parser intelligently skips these dead links and continues processing the available videos, so your batch download isn't ruined by a single broken link.": 'Les playlists contiennent souvent des vidéos qui ont été supprimées, rendues privées ou restreintes dans votre région. Notre analyseur ignore intelligemment ces liens morts et continue à traiter les vidéos disponibles, de sorte que votre téléchargement par lots n\'est pas ruiné par un seul lien cassé.',
    "1. Navigate to the playlist on YouTube. Ensure the URL contains 'list=' (e.g., youtube.com/playlist?list=...). 2. Copy the URL. 3. Paste it into our converter. 4. Select your global format (MP3 or MP4). 5. Click Convert. 6. Wait for the parser to extract the videos, then click the individual download buttons as they appear.": "1. Accédez à la playlist sur YouTube. Assurez-vous que l'URL contient 'list=' (par exemple, youtube.com/playlist?list=...). 2. Copiez l'URL. 3. Collez-la dans notre convertisseur. 4. Sélectionnez votre format global (MP3 ou MP4). 5. Cliquez sur Convertir. 6. Attendez que l'analyseur extraie les vidéos, puis cliquez sur les boutons de téléchargement individuels au fur et à mesure qu'ils apparaissent.",
    'Is there a maximum playlist length?': 'Y a-t-il une longueur maximale de playlist?', 'Are playlists downloaded in order?': 'Les playlists sont-elles téléchargées dans l\'ordre?',
    'Is there a limit to the number of videos in a playlist?': 'Y a-t-il une limite au nombre de vidéos dans une playlist?', 'Will it download as one giant file or separate files?': 'Sera-t-il téléchargé comme un fichier géant ou des fichiers séparés?',
    "Can I download a 'Watch Later' playlist?": "Puis-je télécharger une playlist 'À regarder plus tard'?", 'What happens if the playlist contains a live stream?': 'Que se passe-t-il si la playlist contient un flux en direct?',
    'How long does a 50-video playlist take to convert?': 'Combien de temps faut-il pour convertir une playlist de 50 vidéos?', 'Do I have to click download 50 times?': 'Dois-je cliquer sur télécharger 50 fois?',
    'Does it download the playlist thumbnail?': 'Télécharge-t-il la miniature de la playlist?', "Can I download a channel's entire video list?": 'Puis-je télécharger la liste complète des vidéos d\'une chaîne?',
    'Are the files numbered?': 'Les fichiers sont-ils numérotés?', 'Why did only half the videos appear?': 'Pourquoi seulement la moitié des vidéos sont-elles apparues?',
    'No hard cap, but very large playlists (500+ videos) may take several minutes to process in full.': 'Pas de limite stricte, mais les très grandes playlists (plus de 500 vidéos) peuvent prendre plusieurs minutes à traiter complètement.',
    'Yes. Original playlist ordering is preserved by default.': 'Oui. L\'ordre original de la playlist est préservé par défaut.',
    'We can theoretically parse playlists of any size, but for optimal performance and browser stability, we recommend downloading playlists with 200 videos or fewer at a time.': 'Nous pouvons théoriquement analyser des playlists de n\'importe quelle taille, mais pour des performances optimales et une stabilité du navigateur, nous recommandons de télécharger des playlists avec 200 vidéos ou moins à la fois.',
    'Each video in the playlist is converted and downloaded as its own separate file. We do not merge them into a single massive audio/video file.': 'Chaque vidéo de la playlist est convertie et téléchargée comme son propre fichier séparé. Nous ne les fusionnons pas en un seul fichier audio/vidéo massif.',
    "Your 'Watch Later' playlist is private to your account. Our servers cannot access it. You would need to move those videos to a Public or Unlisted playlist first.": "Votre playlist 'À regarder plus tard' est privée pour votre compte. Nos serveurs ne peuvent pas y accéder. Vous devriez d'abord déplacer ces vidéos vers une playlist publique ou non répertoriée.",
    'If the live stream has ended and is available as a VOD, it will download normally. If the stream is currently live, the tool will skip it, as it has no finite length.': 'Si le flux en direct est terminé et disponible en tant que VOD, il sera téléchargé normalement. Si le flux est actuellement en direct, l\'outil le sautera, car il n\'a pas de longueur finie.',
    'Parsing the list takes only seconds. The conversion time depends on the total length of the videos and the chosen quality, but our concurrent processing usually finishes a typical music playlist in under 3 minutes.': 'L\'analyse de la liste ne prend que quelques secondes. Le temps de conversion dépend de la longueur totale des vidéos et de la qualité choisie, mais notre traitement concurrent termine généralement une playlist musicale typique en moins de 3 minutes.',
    'Currently, browser security restrictions prevent websites from automatically triggering 50 file downloads at once. You will need to click the download button for each generated file.': 'Actuellement, les restrictions de sécurité du navigateur empêchent les sites Web de déclencher automatiquement 50 téléchargements de fichiers à la fois. Vous devrez cliquer sur le bouton de téléchargement pour chaque fichier généré.',
    'The individual video files will have their respective video thumbnails embedded as metadata (for audio formats) or as the poster frame (for video formats).': 'Les fichiers vidéo individuels auront leurs miniatures vidéo respectives intégrées en tant que métadonnées (pour les formats audio) ou en tant qu\'image d\'affiche (pour les formats vidéo).',
    "If the channel has a 'Play All' button or a playlist containing all their uploads, yes. Just copy that specific playlist URL.": "Si la chaîne a un bouton 'Tout lire' ou une playlist contenant tous leurs téléchargements, oui. Copiez simplement cette URL de playlist spécifique.",
    "The files retain their original YouTube titles. If the creator numbered the titles (e.g., 'Episode 1: ...'), that numbering will be in your downloaded file.": "Les fichiers conservent leurs titres YouTube d'origine. Si le créateur a numéroté les titres (par exemple, 'Épisode 1: ...'), cette numérotation sera dans votre fichier téléchargé.",
    'This usually means the missing videos are either Private, Deleted, or Region-Blocked. Our tool can only fetch publicly accessible media.': 'Cela signifie généralement que les vidéos manquantes sont soit privées, supprimées ou bloquées par région. Notre outil ne peut récupérer que les médias accessibles au public.',
    'Bulk-convert every video in a playlist': 'Convertir en masse chaque vidéo d\'une playlist',
    'Paste any public YouTube playlist URL (for example ?list=PL…) and yt2mp3.lol queues every video individually. Each conversion runs in parallel where possible, so even long playlists finish quickly. You get one clean file per video, named with the original title.': 'Collez n\'importe quelle URL de playlist YouTube publique (par exemple ?list=PL…) et yt2mp3.lol met en file d\'attente chaque vidéo individuellement. Chaque conversion s\'exécute en parallèle lorsque cela est possible, de sorte que même les longues playlists se terminent rapidement. Vous obtenez un fichier propre par vidéo, nommé avec le titre original.',
    'Supports mixes and topic playlists': 'Prend en charge les mix et les playlists thématiques',
    'Auto-generated mixes, Topic artist playlists, and user-curated playlists all work as long as they\'re set to Public or Unlisted. Private playlists won\'t resolve.': 'Les mix générés automatiquement, les playlists d\'artistes thématiques et les playlists organisées par les utilisateurs fonctionnent tous tant qu\'ils sont définis sur Public ou Non répertorié. Les playlists privées ne seront pas résolues.',
    'Picking the right format': 'Choisir le bon format',
    'For music, MP3 at 320 kbps is the standard. For podcasts, M4A produces smaller files at equal quality. For lecture series you plan to re-watch, MP4 at 720p balances storage and clarity.': 'Pour la musique, le MP3 à 320 kbps est la norme. Pour les podcasts, le M4A produit des fichiers plus petits à qualité égale. Pour les séries de conférences que vous prévoyez de revoir, le MP4 à 720p équilibre stockage et clarté.',
    'Format Comparison Table': 'Tableau de comparaison des formats',
    'YouTube Shorts Downloader': 'Téléchargeur YouTube Shorts', 'Download YouTube Shorts videos in MP3 or MP4 format. Fast, free, and easy to use.': 'Téléchargez des vidéos YouTube Shorts au format MP3 ou MP4. Rapide, gratuit et facile à utiliser.',
    'youtube shorts downloader, shorts to mp3, download youtube shorts, shorts converter': 'téléchargeur youtube shorts, shorts en mp3, télécharger youtube shorts, convertisseur shorts',
    'YouTube Multi Downloader': 'Téléchargeur multiple YouTube', 'Download multiple YouTube videos at once. Paste multiple URLs and convert them all in one go.': 'Téléchargez plusieurs vidéos YouTube à la fois. Collez plusieurs URL et convertissez-les toutes en une seule fois.',
    'youtube multi downloader, bulk youtube download, multiple youtube videos, batch download': 'téléchargeur multiple youtube, téléchargement en masse youtube, plusieurs vidéos youtube, téléchargement par lots',
}

def t(f):
    c = Path(f).read_text(encoding='utf-8')
    for e, b in french.items(): c = c.replace(e, b)
    Path(f).write_text(c, encoding='utf-8')
    print(f"✓ {f}")

t('web/fr/youtube-playlist-downloader/index.html')
t('web/fr/youtube-shorts-downloader/index.html')
t('web/fr/youtube-multi-downloader/index.html')
print("\n✅ French (fr) complete - 3/3")
