#!/usr/bin/env python3
from pathlib import Path

bengali = {
    'Format': 'ফরম্যাট', 'Best For': 'সেরা জন্য', 'Quality Options': 'গুণমান বিকল্প', 'File Size': 'ফাইল সাইজ',
    'Universal audio playback': 'সর্বজনীন অডিও প্লেব্যাক', 'Small': 'ছোট', 'Video playback everywhere': 'সর্বত্র ভিডিও প্লেব্যাক',
    'Large': 'বড়', 'Lossless audio editing': 'লসলেস অডিও এডিটিং', 'Very Large': 'খুব বড়', 'Apple devices': 'Apple ডিভাইস',
    'Native AAC': 'নেটিভ AAC', 'Medium': 'মাঝারি', 'Batch Conversion Masterclass': 'ব্যাচ রূপান্তর মাস্টারক্লাস',
    'Preserve Original Order and Titles': 'মূল ক্রম এবং শিরোনাম সংরক্ষণ করুন', 'Flexible Format Selection for Playlists': 'প্লেলিস্টের জন্য নমনীয় ফরম্যাট নির্বাচন',
    'High-Concurrency Processing': 'উচ্চ-সমসাময়িক প্রক্রিয়াকরণ', 'Support for Massive Playlists': 'বিশাল প্লেলিস্টের জন্য সমর্থন',
    'Download Auto-Generated Mixes': 'স্বয়ংক্রিয়-উৎপন্ন মিক্স ডাউনলোড করুন', 'Ideal for Educators and Students': 'শিক্ষাবিদ এবং শিক্ষার্থীদের জন্য আদর্শ',
    'Handling Unavailable or Private Videos': 'অনুপলব্ধ বা প্রাইভেট ভিডিও পরিচালনা', 'How to Download a Full Playlist': 'কীভাবে একটি সম্পূর্ণ প্লেলিস্ট ডাউনলোড করবেন',
    'Downloading videos one by one is incredibly tedious. Our YouTube Playlist Downloader is engineered for bulk operations. By parsing the playlist metadata, our servers generate individual conversion jobs for every single video in the list, allowing you to download an entire album, lecture series, or podcast backlog with minimal effort.': 'একের পর এক ভিডিও ডাউনলোড করা অবিশ্বাস্যভাবে ক্লান্তিকর। আমাদের YouTube প্লেলিস্ট ডাউনলোডার বাল্ক অপারেশনের জন্য ইঞ্জিনিয়ার করা হয়েছে। প্লেলিস্ট মেটাডেটা পার্স করে, আমাদের সার্ভার তালিকার প্রতিটি একক ভিডিওর জন্য পৃথক রূপান্তর কাজ তৈরি করে, যা আপনাকে ন্যূনতম প্রচেষ্টায় একটি সম্পূর্ণ অ্যালবাম, লেক্চার সিরিজ বা পডকাস্ট ব্যাকলগ ডাউনলোড করতে দেয়।',
    'When you download a playlist, organization is key. Our system automatically grabs the original video titles and structures the downloads so you can easily maintain the intended order. This is perfect for sequential tutorials, multi-part documentaries, or chronologically ordered music albums.': 'যখন আপনি একটি প্লেলিস্ট ডাউনলোড করেন, সংগঠন মূল চাবিকাঠি। আমাদের সিস্টেম স্বয়ংক্রিয়ভাবে মূল ভিডিও শিরোনাম ধরে এবং ডাউনলোডগুলি গঠন করে যাতে আপনি সহজেই উদ্দিষ্ট ক্রম বজায় রাখতে পারেন। এটি ক্রমিক টিউটোরিয়াল, বহু-অংশ ডকুমেন্টারি বা কালানুক্রমিকভাবে সাজানো সঙ্গীত অ্যালবামের জন্য নিখুঁত।',
    "You aren't locked into a single format. You can choose to download an entire music playlist as crisp 320kbps MP3s, or an entire educational course as 1080p MP4s. Our FFmpeg backend applies your selected format uniformly across all items in the batch.": 'আপনি একটি একক ফরম্যাটে লক নন। আপনি একটি সম্পূর্ণ সঙ্গীত প্লেলিস্ট ক্রিস্প 320kbps MP3 হিসাবে ডাউনলোড করতে পারেন, বা একটি সম্পূর্ণ শিক্ষামূলক কোর্স 1080p MP4 হিসাবে। আমাদের FFmpeg ব্যাকএন্ড ব্যাচের সমস্ত আইটেম জুড়ে আপনার নির্বাচিত ফরম্যাট সমানভাবে প্রয়োগ করে।',
    "We don't make you wait for one video to finish before starting the next. Our cloud infrastructure utilizes high-concurrency processing, meaning multiple videos from your playlist are downloaded and converted simultaneously. A 50-video playlist is processed significantly faster than doing it manually.": 'আমরা আপনাকে পরবর্তী শুরু করার আগে একটি ভিডিও শেষ হওয়ার জন্য অপেক্ষা করাই না। আমাদের ক্লাউড অবকাঠামো উচ্চ-সমসাময়িক প্রক্রিয়াকরণ ব্যবহার করে, যার অর্থ আপনার প্লেলিস্ট থেকে একাধিক ভিডিও একসাথে ডাউনলোড এবং রূপান্তরিত হয়। একটি 50-ভিডিও প্লেলিস্ট ম্যানুয়ালি করার চেয়ে উল্লেখযোগ্যভাবে দ্রুত প্রক্রিয়া করা হয়।',
    "Whether it's a 10-track EP or a massive 300-video mega-mix, our tool is built to handle it. While extremely large playlists may take a few minutes to fully parse and render download buttons, our backend will not time out or crash during the operation.": 'এটি 10-ট্র্যাক EP হোক বা একটি বিশাল 300-ভিডিও মেগা-মিক্স, আমাদের টুল এটি পরিচালনা করার জন্য তৈরি। যদিও অত্যন্ত বড় প্লেলিস্টগুলি সম্পূর্ণরূপে পার্স এবং ডাউনলোড বোতাম রেন্ডার করতে কয়েক মিনিট সময় নিতে পারে, আমাদের ব্যাকএন্ড অপারেশনের সময় টাইম আউট বা ক্র্যাশ হবে না।',
    "Did YouTube's algorithm create the perfect 'My Mix' or 'Discover Weekly' equivalent for you? Just copy the URL of that auto-generated playlist and paste it here. You can rip the entire curated mix to your local device for offline listening on road trips or flights.": "YouTube এর অ্যালগরিদম কি আপনার জন্য নিখুঁত 'My Mix' বা 'Discover Weekly' সমতুল্য তৈরি করেছে? শুধু সেই স্বয়ংক্রিয়-উৎপন্ন প্লেলিস্টের URL কপি করুন এবং এখানে পেস্ট করুন। আপনি রোড ট্রিপ বা ফ্লাইটে অফলাইন শোনার জন্য আপনার স্থানীয় ডিভাইসে সম্পূর্ণ কিউরেটেড মিক্স রিপ করতে পারেন।",
    'Many professors and online instructors organize their course modules into public YouTube playlists. Students can use our tool to download the entire semester\'s worth of lectures in MP4 format, ensuring they have access to study materials even without an internet connection.': 'অনেক অধ্যাপক এবং অনলাইন প্রশিক্ষক তাদের কোর্স মডিউলগুলি পাবলিক YouTube প্লেলিস্টে সংগঠিত করেন। শিক্ষার্থীরা আমাদের টুল ব্যবহার করে MP4 ফরম্যাটে সম্পূর্ণ সেমিস্টারের লেকচার ডাউনলোড করতে পারে, নিশ্চিত করে যে তাদের ইন্টারনেট সংযোগ ছাড়াই অধ্যয়ন উপকরণে অ্যাক্সেস আছে।',
    "Playlists often contain videos that have been deleted, made private, or restricted in your region. Our parser intelligently skips these dead links and continues processing the available videos, so your batch download isn't ruined by a single broken link.": 'প্লেলিস্টগুলিতে প্রায়শই এমন ভিডিও থাকে যা মুছে ফেলা হয়েছে, প্রাইভেট করা হয়েছে বা আপনার অঞ্চলে সীমাবদ্ধ। আমাদের পার্সার বুদ্ধিমানভাবে এই মৃত লিঙ্কগুলি এড়িয়ে যায় এবং উপলব্ধ ভিডিওগুলি প্রক্রিয়া করা চালিয়ে যায়, তাই আপনার ব্যাচ ডাউনলোড একটি একক ভাঙা লিঙ্ক দ্বারা নষ্ট হয় না।',
    "1. Navigate to the playlist on YouTube. Ensure the URL contains 'list=' (e.g., youtube.com/playlist?list=...). 2. Copy the URL. 3. Paste it into our converter. 4. Select your global format (MP3 or MP4). 5. Click Convert. 6. Wait for the parser to extract the videos, then click the individual download buttons as they appear.": "1. YouTube এ প্লেলিস্টে নেভিগেট করুন। নিশ্চিত করুন যে URL এ 'list=' রয়েছে (যেমন, youtube.com/playlist?list=...)। 2. URL কপি করুন। 3. এটি আমাদের কনভার্টারে পেস্ট করুন। 4. আপনার গ্লোবাল ফরম্যাট (MP3 বা MP4) নির্বাচন করুন। 5. রূপান্তর করুন ক্লিক করুন। 6. পার্সার ভিডিওগুলি এক্সট্র্যাক্ট করার জন্য অপেক্ষা করুন, তারপর তারা উপস্থিত হওয়ার সাথে সাথে পৃথক ডাউনলোড বোতামগুলিতে ক্লিক করুন।",
    'Is there a maximum playlist length?': 'প্লেলিস্টের সর্বোচ্চ দৈর্ঘ্য আছে কি?', 'Are playlists downloaded in order?': 'প্লেলিস্ট কি ক্রমানুসারে ডাউনলোড হয়?',
    'Is there a limit to the number of videos in a playlist?': 'প্লেলিস্টে ভিডিওর সংখ্যার সীমা আছে কি?', 'Will it download as one giant file or separate files?': 'এটি কি একটি বিশাল ফাইল বা আলাদা ফাইল হিসাবে ডাউনলোড হবে?',
    "Can I download a 'Watch Later' playlist?": "আমি কি 'Watch Later' প্লেলিস্ট ডাউনলোড করতে পারি?", 'What happens if the playlist contains a live stream?': 'প্লেলিস্টে লাইভ স্ট্রিম থাকলে কী হয়?',
    'How long does a 50-video playlist take to convert?': '50-ভিডিও প্লেলিস্ট রূপান্তর করতে কতক্ষণ সময় লাগে?', 'Do I have to click download 50 times?': 'আমাকে কি 50 বার ডাউনলোড ক্লিক করতে হবে?',
    'Does it download the playlist thumbnail?': 'এটি কি প্লেলিস্ট থাম্বনেইল ডাউনলোড করে?', "Can I download a channel's entire video list?": 'আমি কি একটি চ্যানেলের সম্পূর্ণ ভিডিও তালিকা ডাউনলোড করতে পারি?',
    'Are the files numbered?': 'ফাইলগুলি কি নম্বরযুক্ত?', 'Why did only half the videos appear?': 'কেন শুধুমাত্র অর্ধেক ভিডিও উপস্থিত হয়েছে?',
    'No hard cap, but very large playlists (500+ videos) may take several minutes to process in full.': 'কোন হার্ড ক্যাপ নেই, তবে খুব বড় প্লেলিস্ট (500+ ভিডিও) সম্পূর্ণরূপে প্রক্রিয়া করতে কয়েক মিনিট সময় নিতে পারে।',
    'Yes. Original playlist ordering is preserved by default.': 'হ্যাঁ। মূল প্লেলিস্ট ক্রম ডিফল্টভাবে সংরক্ষিত থাকে।',
    'We can theoretically parse playlists of any size, but for optimal performance and browser stability, we recommend downloading playlists with 200 videos or fewer at a time.': 'আমরা তাত্ত্বিকভাবে যেকোনো আকারের প্লেলিস্ট পার্স করতে পারি, তবে সর্বোত্তম কর্মক্ষমতা এবং ব্রাউজার স্থিতিশীলতার জন্য, আমরা একবারে 200 বা তার কম ভিডিও সহ প্লেলিস্ট ডাউনলোড করার পরামর্শ দিই।',
    'Each video in the playlist is converted and downloaded as its own separate file. We do not merge them into a single massive audio/video file.': 'প্লেলিস্টের প্রতিটি ভিডিও তার নিজস্ব আলাদা ফাইল হিসাবে রূপান্তরিত এবং ডাউনলোড হয়। আমরা তাদের একটি একক বিশাল অডিও/ভিডিও ফাইলে মার্জ করি না।',
    "Your 'Watch Later' playlist is private to your account. Our servers cannot access it. You would need to move those videos to a Public or Unlisted playlist first.": "আপনার 'Watch Later' প্লেলিস্ট আপনার অ্যাকাউন্টে প্রাইভেট। আমাদের সার্ভার এটি অ্যাক্সেস করতে পারে না। আপনাকে প্রথমে সেই ভিডিওগুলি একটি পাবলিক বা আনলিস্টেড প্লেলিস্টে সরাতে হবে।",
    'If the live stream has ended and is available as a VOD, it will download normally. If the stream is currently live, the tool will skip it, as it has no finite length.': 'যদি লাইভ স্ট্রিম শেষ হয়ে যায় এবং VOD হিসাবে উপলব্ধ থাকে, এটি স্বাভাবিকভাবে ডাউনলোড হবে। যদি স্ট্রিম বর্তমানে লাইভ থাকে, টুল এটি এড়িয়ে যাবে, কারণ এর কোন সীমিত দৈর্ঘ্য নেই।',
    'Parsing the list takes only seconds. The conversion time depends on the total length of the videos and the chosen quality, but our concurrent processing usually finishes a typical music playlist in under 3 minutes.': 'তালিকা পার্স করতে মাত্র কয়েক সেকেন্ড সময় লাগে। রূপান্তর সময় ভিডিওগুলির মোট দৈর্ঘ্য এবং নির্বাচিত গুণমানের উপর নির্ভর করে, তবে আমাদের সমসাময়িক প্রক্রিয়াকরণ সাধারণত একটি সাধারণ সঙ্গীত প্লেলিস্ট 3 মিনিটের মধ্যে শেষ করে।',
    'Currently, browser security restrictions prevent websites from automatically triggering 50 file downloads at once. You will need to click the download button for each generated file.': 'বর্তমানে, ব্রাউজার নিরাপত্তা সীমাবদ্ধতা ওয়েবসাইটগুলিকে একবারে 50টি ফাইল ডাউনলোড স্বয়ংক্রিয়ভাবে ট্রিগার করতে বাধা দেয়। আপনাকে প্রতিটি উৎপন্ন ফাইলের জন্য ডাউনলোড বোতামে ক্লিক করতে হবে।',
    'The individual video files will have their respective video thumbnails embedded as metadata (for audio formats) or as the poster frame (for video formats).': 'পৃথক ভিডিও ফাইলগুলিতে তাদের নিজ নিজ ভিডিও থাম্বনেইল মেটাডেটা হিসাবে এম্বেড করা থাকবে (অডিও ফরম্যাটের জন্য) বা পোস্টার ফ্রেম হিসাবে (ভিডিও ফরম্যাটের জন্য)।',
    "If the channel has a 'Play All' button or a playlist containing all their uploads, yes. Just copy that specific playlist URL.": "যদি চ্যানেলে 'Play All' বোতাম থাকে বা তাদের সমস্ত আপলোড সম্বলিত একটি প্লেলিস্ট থাকে, হ্যাঁ। শুধু সেই নির্দিষ্ট প্লেলিস্ট URL কপি করুন।",
    "The files retain their original YouTube titles. If the creator numbered the titles (e.g., 'Episode 1: ...'), that numbering will be in your downloaded file.": "ফাইলগুলি তাদের মূল YouTube শিরোনাম ধরে রাখে। যদি নির্মাতা শিরোনামগুলি নম্বর করে থাকেন (যেমন, 'Episode 1: ...'), সেই নম্বরিং আপনার ডাউনলোড করা ফাইলে থাকবে।",
    'This usually means the missing videos are either Private, Deleted, or Region-Blocked. Our tool can only fetch publicly accessible media.': 'এর সাধারণত মানে হল অনুপস্থিত ভিডিওগুলি হয় প্রাইভেট, মুছে ফেলা বা অঞ্চল-ব্লক করা। আমাদের টুল শুধুমাত্র সর্বজনীনভাবে অ্যাক্সেসযোগ্য মিডিয়া আনতে পারে।',
    'YouTube Shorts Downloader': 'YouTube Shorts ডাউনলোডার', 'Download YouTube Shorts videos in MP3 or MP4 format. Fast, free, and easy to use.': 'YouTube Shorts ভিডিও MP3 বা MP4 ফরম্যাটে ডাউনলোড করুন। দ্রুত, বিনামূল্যে এবং ব্যবহার করা সহজ।',
    'youtube shorts downloader, shorts to mp3, download youtube shorts, shorts converter': 'youtube shorts downloader, shorts to mp3, download youtube shorts, shorts converter, ইউটিউব শর্টস ডাউনলোড, শর্টস থেকে mp3',
    'YouTube Multi Downloader': 'YouTube মাল্টি ডাউনলোডার', 'Download multiple YouTube videos at once. Paste multiple URLs and convert them all in one go.': 'একসাথে একাধিক YouTube ভিডিও ডাউনলোড করুন। একাধিক URL পেস্ট করুন এবং সবগুলি একবারে রূপান্তর করুন।',
    'youtube multi downloader, bulk youtube download, multiple youtube videos, batch download': 'youtube multi downloader, bulk youtube download, multiple youtube videos, batch download, একাধিক ইউটিউব ডাউনলোড, বাল্ক ডাউনলোড',
}

def t(f):
    c = Path(f).read_text(encoding='utf-8')
    for e, b in bengali.items(): c = c.replace(e, b)
    Path(f).write_text(c, encoding='utf-8')
    print(f"✓ {f}")

t('web/bn/youtube-playlist-downloader/index.html')
t('web/bn/youtube-shorts-downloader/index.html')
t('web/bn/youtube-multi-downloader/index.html')
print("\n✅ Bengali (bn) complete - 3/3")
