#!/usr/bin/env python3
from pathlib import Path

indonesian = {
    'Format': 'Format', 'Best For': 'Terbaik Untuk', 'Quality Options': 'Opsi Kualitas', 'File Size': 'Ukuran File',
    'Universal audio playback': 'Pemutaran audio universal', 'Small': 'Kecil', 'Video playback everywhere': 'Pemutaran video di mana saja',
    'Large': 'Besar', 'Lossless audio editing': 'Pengeditan audio lossless', 'Very Large': 'Sangat Besar', 'Apple devices': 'Perangkat Apple',
    'Native AAC': 'AAC Native', 'Medium': 'Sedang', 'Batch Conversion Masterclass': 'Masterclass Konversi Batch',
    'Preserve Original Order and Titles': 'Pertahankan Urutan dan Judul Asli', 'Flexible Format Selection for Playlists': 'Pemilihan Format Fleksibel untuk Playlist',
    'High-Concurrency Processing': 'Pemrosesan Konkurensi Tinggi', 'Support for Massive Playlists': 'Dukungan untuk Playlist Masif',
    'Download Auto-Generated Mixes': 'Unduh Mix yang Dibuat Otomatis', 'Ideal for Educators and Students': 'Ideal untuk Pendidik dan Siswa',
    'Handling Unavailable or Private Videos': 'Menangani Video yang Tidak Tersedia atau Pribadi', 'How to Download a Full Playlist': 'Cara Mengunduh Playlist Lengkap',
    'Downloading videos one by one is incredibly tedious. Our YouTube Playlist Downloader is engineered for bulk operations. By parsing the playlist metadata, our servers generate individual conversion jobs for every single video in the list, allowing you to download an entire album, lecture series, or podcast backlog with minimal effort.': 'Mengunduh video satu per satu sangat membosankan. YouTube Playlist Downloader kami dirancang untuk operasi massal. Dengan mengurai metadata playlist, server kami menghasilkan pekerjaan konversi individual untuk setiap video dalam daftar, memungkinkan Anda mengunduh seluruh album, seri kuliah, atau backlog podcast dengan usaha minimal.',
    'When you download a playlist, organization is key. Our system automatically grabs the original video titles and structures the downloads so you can easily maintain the intended order. This is perfect for sequential tutorials, multi-part documentaries, or chronologically ordered music albums.': 'Saat Anda mengunduh playlist, organisasi adalah kuncinya. Sistem kami secara otomatis mengambil judul video asli dan menyusun unduhan sehingga Anda dapat dengan mudah mempertahankan urutan yang dimaksud. Ini sempurna untuk tutorial berurutan, dokumenter multi-bagian, atau album musik yang diurutkan secara kronologis.',
    "You aren't locked into a single format. You can choose to download an entire music playlist as crisp 320kbps MP3s, or an entire educational course as 1080p MP4s. Our FFmpeg backend applies your selected format uniformly across all items in the batch.": 'Anda tidak terkunci dalam satu format. Anda dapat memilih untuk mengunduh seluruh playlist musik sebagai MP3 320kbps yang jernih, atau seluruh kursus pendidikan sebagai MP4 1080p. Backend FFmpeg kami menerapkan format yang Anda pilih secara seragam di semua item dalam batch.',
    "We don't make you wait for one video to finish before starting the next. Our cloud infrastructure utilizes high-concurrency processing, meaning multiple videos from your playlist are downloaded and converted simultaneously. A 50-video playlist is processed significantly faster than doing it manually.": 'Kami tidak membuat Anda menunggu satu video selesai sebelum memulai yang berikutnya. Infrastruktur cloud kami menggunakan pemrosesan konkurensi tinggi, yang berarti beberapa video dari playlist Anda diunduh dan dikonversi secara bersamaan. Playlist 50 video diproses jauh lebih cepat daripada melakukannya secara manual.',
    "Whether it's a 10-track EP or a massive 300-video mega-mix, our tool is built to handle it. While extremely large playlists may take a few minutes to fully parse and render download buttons, our backend will not time out or crash during the operation.": 'Baik itu EP 10 trek atau mega-mix 300 video yang masif, alat kami dibangun untuk menanganinya. Meskipun playlist yang sangat besar mungkin memerlukan beberapa menit untuk sepenuhnya diurai dan merender tombol unduh, backend kami tidak akan timeout atau crash selama operasi.',
    "Did YouTube's algorithm create the perfect 'My Mix' or 'Discover Weekly' equivalent for you? Just copy the URL of that auto-generated playlist and paste it here. You can rip the entire curated mix to your local device for offline listening on road trips or flights.": "Apakah algoritma YouTube membuat 'My Mix' atau 'Discover Weekly' yang sempurna untuk Anda? Cukup salin URL playlist yang dibuat otomatis itu dan tempelkan di sini. Anda dapat menyalin seluruh mix yang dikurasi ke perangkat lokal Anda untuk mendengarkan offline saat perjalanan darat atau penerbangan.",
    'Many professors and online instructors organize their course modules into public YouTube playlists. Students can use our tool to download the entire semester\'s worth of lectures in MP4 format, ensuring they have access to study materials even without an internet connection.': 'Banyak profesor dan instruktur online mengatur modul kursus mereka ke dalam playlist YouTube publik. Siswa dapat menggunakan alat kami untuk mengunduh kuliah senilai satu semester penuh dalam format MP4, memastikan mereka memiliki akses ke materi studi bahkan tanpa koneksi internet.',
    "Playlists often contain videos that have been deleted, made private, or restricted in your region. Our parser intelligently skips these dead links and continues processing the available videos, so your batch download isn't ruined by a single broken link.": 'Playlist sering berisi video yang telah dihapus, dibuat pribadi, atau dibatasi di wilayah Anda. Parser kami secara cerdas melewati tautan mati ini dan terus memproses video yang tersedia, sehingga unduhan batch Anda tidak rusak oleh satu tautan yang rusak.',
    "1. Navigate to the playlist on YouTube. Ensure the URL contains 'list=' (e.g., youtube.com/playlist?list=...). 2. Copy the URL. 3. Paste it into our converter. 4. Select your global format (MP3 or MP4). 5. Click Convert. 6. Wait for the parser to extract the videos, then click the individual download buttons as they appear.": "1. Navigasi ke playlist di YouTube. Pastikan URL berisi 'list=' (misalnya, youtube.com/playlist?list=...). 2. Salin URL. 3. Tempelkan ke konverter kami. 4. Pilih format global Anda (MP3 atau MP4). 5. Klik Konversi. 6. Tunggu parser mengekstrak video, lalu klik tombol unduh individual saat muncul.",
    'Is there a maximum playlist length?': 'Apakah ada panjang playlist maksimum?', 'Are playlists downloaded in order?': 'Apakah playlist diunduh secara berurutan?',
    'Is there a limit to the number of videos in a playlist?': 'Apakah ada batasan jumlah video dalam playlist?', 'Will it download as one giant file or separate files?': 'Apakah akan diunduh sebagai satu file raksasa atau file terpisah?',
    "Can I download a 'Watch Later' playlist?": "Bisakah saya mengunduh playlist 'Tonton Nanti'?", 'What happens if the playlist contains a live stream?': 'Apa yang terjadi jika playlist berisi live stream?',
    'How long does a 50-video playlist take to convert?': 'Berapa lama waktu yang dibutuhkan untuk mengonversi playlist 50 video?', 'Do I have to click download 50 times?': 'Apakah saya harus mengklik unduh 50 kali?',
    'Does it download the playlist thumbnail?': 'Apakah mengunduh thumbnail playlist?', "Can I download a channel's entire video list?": 'Bisakah saya mengunduh seluruh daftar video saluran?',
    'Are the files numbered?': 'Apakah file diberi nomor?', 'Why did only half the videos appear?': 'Mengapa hanya setengah video yang muncul?',
    'No hard cap, but very large playlists (500+ videos) may take several minutes to process in full.': 'Tidak ada batas keras, tetapi playlist yang sangat besar (500+ video) mungkin memerlukan beberapa menit untuk diproses sepenuhnya.',
    'Yes. Original playlist ordering is preserved by default.': 'Ya. Urutan playlist asli dipertahankan secara default.',
    'We can theoretically parse playlists of any size, but for optimal performance and browser stability, we recommend downloading playlists with 200 videos or fewer at a time.': 'Kami secara teoritis dapat mengurai playlist dengan ukuran berapa pun, tetapi untuk kinerja optimal dan stabilitas browser, kami merekomendasikan mengunduh playlist dengan 200 video atau lebih sedikit sekaligus.',
    'Each video in the playlist is converted and downloaded as its own separate file. We do not merge them into a single massive audio/video file.': 'Setiap video dalam playlist dikonversi dan diunduh sebagai file terpisahnya sendiri. Kami tidak menggabungkannya menjadi satu file audio/video masif.',
    "Your 'Watch Later' playlist is private to your account. Our servers cannot access it. You would need to move those videos to a Public or Unlisted playlist first.": "Playlist 'Tonton Nanti' Anda bersifat pribadi untuk akun Anda. Server kami tidak dapat mengaksesnya. Anda perlu memindahkan video tersebut ke playlist Publik atau Tidak Terdaftar terlebih dahulu.",
    'If the live stream has ended and is available as a VOD, it will download normally. If the stream is currently live, the tool will skip it, as it has no finite length.': 'Jika live stream telah berakhir dan tersedia sebagai VOD, itu akan diunduh secara normal. Jika stream saat ini sedang live, alat akan melewatinya, karena tidak memiliki panjang yang terbatas.',
    'Parsing the list takes only seconds. The conversion time depends on the total length of the videos and the chosen quality, but our concurrent processing usually finishes a typical music playlist in under 3 minutes.': 'Mengurai daftar hanya membutuhkan beberapa detik. Waktu konversi tergantung pada panjang total video dan kualitas yang dipilih, tetapi pemrosesan bersamaan kami biasanya menyelesaikan playlist musik tipikal dalam waktu kurang dari 3 menit.',
    'Currently, browser security restrictions prevent websites from automatically triggering 50 file downloads at once. You will need to click the download button for each generated file.': 'Saat ini, pembatasan keamanan browser mencegah situs web secara otomatis memicu 50 unduhan file sekaligus. Anda perlu mengklik tombol unduh untuk setiap file yang dihasilkan.',
    'The individual video files will have their respective video thumbnails embedded as metadata (for audio formats) or as the poster frame (for video formats).': 'File video individual akan memiliki thumbnail video masing-masing yang tertanam sebagai metadata (untuk format audio) atau sebagai frame poster (untuk format video).',
    "If the channel has a 'Play All' button or a playlist containing all their uploads, yes. Just copy that specific playlist URL.": "Jika saluran memiliki tombol 'Putar Semua' atau playlist yang berisi semua unggahan mereka, ya. Cukup salin URL playlist spesifik itu.",
    "The files retain their original YouTube titles. If the creator numbered the titles (e.g., 'Episode 1: ...'), that numbering will be in your downloaded file.": "File mempertahankan judul YouTube asli mereka. Jika pembuat memberi nomor pada judul (misalnya, 'Episode 1: ...'), penomoran itu akan ada di file yang Anda unduh.",
    'This usually means the missing videos are either Private, Deleted, or Region-Blocked. Our tool can only fetch publicly accessible media.': 'Ini biasanya berarti video yang hilang adalah Pribadi, Dihapus, atau Diblokir Wilayah. Alat kami hanya dapat mengambil media yang dapat diakses publik.',
    'Bulk-convert every video in a playlist': 'Konversi massal setiap video dalam playlist',
    'Paste any public YouTube playlist URL (for example ?list=PL…) and yt2mp3.lol queues every video individually. Each conversion runs in parallel where possible, so even long playlists finish quickly. You get one clean file per video, named with the original title.': 'Tempelkan URL playlist YouTube publik apa pun (misalnya ?list=PL…) dan yt2mp3.lol mengantri setiap video secara individual. Setiap konversi berjalan secara paralel jika memungkinkan, sehingga bahkan playlist panjang selesai dengan cepat. Anda mendapatkan satu file bersih per video, diberi nama dengan judul asli.',
    'Supports mixes and topic playlists': 'Mendukung mix dan playlist topik',
    'Auto-generated mixes, Topic artist playlists, and user-curated playlists all work as long as they\'re set to Public or Unlisted. Private playlists won\'t resolve.': 'Mix yang dibuat otomatis, playlist artis Topik, dan playlist yang dikurasi pengguna semuanya berfungsi selama diatur ke Publik atau Tidak Terdaftar. Playlist pribadi tidak akan terselesaikan.',
    'Picking the right format': 'Memilih format yang tepat',
    'For music, MP3 at 320 kbps is the standard. For podcasts, M4A produces smaller files at equal quality. For lecture series you plan to re-watch, MP4 at 720p balances storage and clarity.': 'Untuk musik, MP3 pada 320 kbps adalah standar. Untuk podcast, M4A menghasilkan file yang lebih kecil dengan kualitas yang sama. Untuk seri kuliah yang Anda rencanakan untuk ditonton ulang, MP4 pada 720p menyeimbangkan penyimpanan dan kejelasan.',
    'Format Comparison Table': 'Tabel Perbandingan Format',
    'YouTube Shorts Downloader': 'Pengunduh YouTube Shorts', 'Download YouTube Shorts videos in MP3 or MP4 format. Fast, free, and easy to use.': 'Unduh video YouTube Shorts dalam format MP3 atau MP4. Cepat, gratis, dan mudah digunakan.',
    'youtube shorts downloader, shorts to mp3, download youtube shorts, shorts converter': 'pengunduh youtube shorts, shorts ke mp3, unduh youtube shorts, konverter shorts',
    'YouTube Multi Downloader': 'Pengunduh Multi YouTube', 'Download multiple YouTube videos at once. Paste multiple URLs and convert them all in one go.': 'Unduh beberapa video YouTube sekaligus. Tempelkan beberapa URL dan konversi semuanya sekaligus.',
    'youtube multi downloader, bulk youtube download, multiple youtube videos, batch download': 'pengunduh multi youtube, unduhan massal youtube, beberapa video youtube, unduhan batch',
}

def t(f):
    c = Path(f).read_text(encoding='utf-8')
    for e, b in indonesian.items(): c = c.replace(e, b)
    Path(f).write_text(c, encoding='utf-8')
    print(f"✓ {f}")

t('web/id/youtube-playlist-downloader/index.html')
t('web/id/youtube-shorts-downloader/index.html')
t('web/id/youtube-multi-downloader/index.html')
print("\n✅ Indonesian (id) complete - 3/3")
