#!/usr/bin/env python3
"""
Translate all remaining playlist pages - Japanese, Korean, Russian, Thai, Turkish, Urdu, Vietnamese
"""

import re
from pathlib import Path

# Full translation dictionaries
translations = {
    'ja': {  # Japanese
        'Home': 'ホーム',
        'Convert an entire YouTube playlist to MP3 or MP4 in one click. Each video downloads as its own file.': 'YouTubeプレイリスト全体をワンクリックでMP3またはMP4に変換。各動画は個別のファイルとしてダウンロードされます。',
        'YT2MP3 - YouTube to MP3': 'YT2MP3 - YouTubeからMP3へ',
        'Paste YouTube URL or search keywords': 'YouTube URLを貼り付けるかキーワードを検索',
        'Paste a YouTube link': 'YouTubeリンクを貼り付け',
        'Paste from clipboard': 'クリップボードから貼り付け',
        'Paste': '貼り付け',
        'Output format': '出力形式',
        'Quality': '品質',
        'Audio track': 'オーディオトラック',
        'Origin': 'オリジナル',
        'Search languages...': '言語を検索...',
        'Origin (default)': 'オリジナル（デフォルト）',
        'Convert': '変換',
        'Bulk-convert every video in a playlist': 'プレイリスト内のすべての動画を一括変換',
        'Supports mixes and topic playlists': 'ミックスとトピックプレイリストをサポート',
        'Picking the right format': '適切な形式の選択',
        'Format Comparison Table': 'フォーマット比較表',
        'Format': 'フォーマット',
        'Best For': '最適な用途',
        'Quality Options': '品質オプション',
        'File Size': 'ファイルサイズ',
        'Universal audio playback': 'ユニバーサルオーディオ再生',
        'Small': '小',
        'Video playback everywhere': 'どこでもビデオ再生',
        'Large': '大',
        'Lossless audio editing': 'ロスレスオーディオ編集',
        'Very Large': '非常に大',
        'Apple devices': 'Appleデバイス',
        'Medium': '中',
        'Batch Conversion Masterclass': 'バッチ変換マスタークラス',
        'Preserve Original Order and Titles': '元の順序とタイトルを保持',
        'Flexible Format Selection for Playlists': 'プレイリストの柔軟な形式選択',
        'High-Concurrency Processing': '高並行処理',
        'Support for Massive Playlists': '大規模プレイリストのサポート',
        'Download Auto-Generated Mixes': '自動生成ミックスをダウンロード',
        'Ideal for Educators and Students': '教育者と学生に最適',
        'Handling Unavailable or Private Videos': '利用不可またはプライベート動画の処理',
        'How to Download a Full Playlist': '完全なプレイリストをダウンロードする方法',
        'FAQ': 'よくある質問',
        'youtube playlist downloader, playlist to mp3, youtube playlist to mp4, batch youtube converter': 'youtube playlist downloader, playlist to mp3, youtube playlist to mp4, batch youtube converter, youtubeプレイリストダウンロード, プレイリストをmp3に',
    },
    'ko': {  # Korean
        'Home': '홈',
        'Convert an entire YouTube playlist to MP3 or MP4 in one click. Each video downloads as its own file.': '한 번의 클릭으로 전체 YouTube 재생목록을 MP3 또는 MP4로 변환하세요. 각 동영상은 개별 파일로 다운로드됩니다.',
        'YT2MP3 - YouTube to MP3': 'YT2MP3 - YouTube를 MP3로',
        'Paste YouTube URL or search keywords': 'YouTube URL을 붙여넣거나 키워드 검색',
        'Paste a YouTube link': 'YouTube 링크 붙여넣기',
        'Paste from clipboard': '클립보드에서 붙여넣기',
        'Paste': '붙여넣기',
        'Output format': '출력 형식',
        'Quality': '품질',
        'Audio track': '오디오 트랙',
        'Origin': '원본',
        'Search languages...': '언어 검색...',
        'Origin (default)': '원본 (기본값)',
        'Convert': '변환',
        'Bulk-convert every video in a playlist': '재생목록의 모든 동영상 일괄 변환',
        'Supports mixes and topic playlists': '믹스 및 주제 재생목록 지원',
        'Picking the right format': '올바른 형식 선택',
        'Format Comparison Table': '형식 비교표',
        'Format': '형식',
        'Best For': '최적 용도',
        'Quality Options': '품질 옵션',
        'File Size': '파일 크기',
        'Universal audio playback': '범용 오디오 재생',
        'Small': '작음',
        'Video playback everywhere': '어디서나 비디오 재생',
        'Large': '큼',
        'Lossless audio editing': '무손실 오디오 편집',
        'Very Large': '매우 큼',
        'Apple devices': 'Apple 기기',
        'Medium': '중간',
        'Batch Conversion Masterclass': '일괄 변환 마스터클래스',
        'Preserve Original Order and Titles': '원래 순서 및 제목 유지',
        'Flexible Format Selection for Playlists': '재생목록을 위한 유연한 형식 선택',
        'High-Concurrency Processing': '고동시성 처리',
        'Support for Massive Playlists': '대규모 재생목록 지원',
        'Download Auto-Generated Mixes': '자동 생성 믹스 다운로드',
        'Ideal for Educators and Students': '교육자와 학생에게 이상적',
        'Handling Unavailable or Private Videos': '사용할 수 없거나 비공개 동영상 처리',
        'How to Download a Full Playlist': '전체 재생목록 다운로드 방법',
        'FAQ': 'FAQ',
        'youtube playlist downloader, playlist to mp3, youtube playlist to mp4, batch youtube converter': 'youtube playlist downloader, playlist to mp3, youtube playlist to mp4, batch youtube converter, 유튜브 재생목록 다운로드, 재생목록을 mp3로',
    },
    'ru': {  # Russian
        'Home': 'Главная',
        'Convert an entire YouTube playlist to MP3 or MP4 in one click. Each video downloads as its own file.': 'Конвертируйте весь плейлист YouTube в MP3 или MP4 одним кликом. Каждое видео загружается как отдельный файл.',
        'YT2MP3 - YouTube to MP3': 'YT2MP3 - YouTube в MP3',
        'Paste YouTube URL or search keywords': 'Вставьте URL YouTube или ключевые слова для поиска',
        'Paste a YouTube link': 'Вставьте ссылку YouTube',
        'Paste from clipboard': 'Вставить из буфера обмена',
        'Paste': 'Вставить',
        'Output format': 'Формат вывода',
        'Quality': 'Качество',
        'Audio track': 'Аудиодорожка',
        'Origin': 'Оригинал',
        'Search languages...': 'Поиск языков...',
        'Origin (default)': 'Оригинал (по умолчанию)',
        'Convert': 'Конвертировать',
        'Bulk-convert every video in a playlist': 'Массовая конвертация всех видео в плейлисте',
        'Supports mixes and topic playlists': 'Поддержка миксов и тематических плейлистов',
        'Picking the right format': 'Выбор правильного формата',
        'Format Comparison Table': 'Таблица сравнения форматов',
        'Format': 'Формат',
        'Best For': 'Лучше всего для',
        'Quality Options': 'Параметры качества',
        'File Size': 'Размер файла',
        'Universal audio playback': 'Универсальное воспроизведение аудио',
        'Small': 'Маленький',
        'Video playback everywhere': 'Воспроизведение видео везде',
        'Large': 'Большой',
        'Lossless audio editing': 'Редактирование аудио без потерь',
        'Very Large': 'Очень большой',
        'Apple devices': 'Устройства Apple',
        'Medium': 'Средний',
        'Batch Conversion Masterclass': 'Мастер-класс по пакетной конвертации',
        'Preserve Original Order and Titles': 'Сохранение исходного порядка и названий',
        'Flexible Format Selection for Playlists': 'Гибкий выбор формата для плейлистов',
        'High-Concurrency Processing': 'Высокопараллельная обработка',
        'Support for Massive Playlists': 'Поддержка массивных плейлистов',
        'Download Auto-Generated Mixes': 'Загрузка автоматически созданных миксов',
        'Ideal for Educators and Students': 'Идеально для преподавателей и студентов',
        'Handling Unavailable or Private Videos': 'Обработка недоступных или приватных видео',
        'How to Download a Full Playlist': 'Как скачать полный плейлист',
        'FAQ': 'FAQ',
        'youtube playlist downloader, playlist to mp3, youtube playlist to mp4, batch youtube converter': 'youtube playlist downloader, playlist to mp3, youtube playlist to mp4, batch youtube converter, скачать плейлист youtube, плейлист в mp3',
    },
    'th': {  # Thai
        'Home': 'หน้าแรก',
        'Convert an entire YouTube playlist to MP3 or MP4 in one click. Each video downloads as its own file.': 'แปลงเพลย์ลิสต์ YouTube ทั้งหมดเป็น MP3 หรือ MP4 ด้วยคลิกเดียว แต่ละวิดีโอดาวน์โหลดเป็นไฟล์แยก',
        'YT2MP3 - YouTube to MP3': 'YT2MP3 - YouTube เป็น MP3',
        'Paste YouTube URL or search keywords': 'วาง URL YouTube หรือค้นหาคำสำคัญ',
        'Paste a YouTube link': 'วางลิงก์ YouTube',
        'Paste from clipboard': 'วางจากคลิปบอร์ด',
        'Paste': 'วาง',
        'Output format': 'รูปแบบเอาต์พุต',
        'Quality': 'คุณภาพ',
        'Audio track': 'แทร็กเสียง',
        'Origin': 'ต้นฉบับ',
        'Search languages...': 'ค้นหาภาษา...',
        'Origin (default)': 'ต้นฉบับ (ค่าเริ่มต้น)',
        'Convert': 'แปลง',
        'Bulk-convert every video in a playlist': 'แปลงวิดีโอทุกรายการในเพลย์ลิสต์แบบกลุ่ม',
        'Supports mixes and topic playlists': 'รองรับมิกซ์และเพลย์ลิสต์หัวข้อ',
        'Picking the right format': 'เลือกรูปแบบที่เหมาะสม',
        'Format Comparison Table': 'ตารางเปรียบเทียบรูปแบบ',
        'Format': 'รูปแบบ',
        'Best For': 'เหมาะสำหรับ',
        'Quality Options': 'ตัวเลือกคุณภาพ',
        'File Size': 'ขนาดไฟล์',
        'Universal audio playback': 'เล่นเสียงได้ทุกที่',
        'Small': 'เล็ก',
        'Video playback everywhere': 'เล่นวิดีโอได้ทุกที่',
        'Large': 'ใหญ่',
        'Lossless audio editing': 'แก้ไขเสียงแบบไม่สูญเสียคุณภาพ',
        'Very Large': 'ใหญ่มาก',
        'Apple devices': 'อุปกรณ์ Apple',
        'Medium': 'ปานกลาง',
        'Batch Conversion Masterclass': 'มาสเตอร์คลาสการแปลงแบบกลุ่ม',
        'Preserve Original Order and Titles': 'รักษาลำดับและชื่อเดิม',
        'Flexible Format Selection for Playlists': 'เลือกรูปแบบที่ยืดหยุ่นสำหรับเพลย์ลิสต์',
        'High-Concurrency Processing': 'การประมวลผลพร้อมกันสูง',
        'Support for Massive Playlists': 'รองรับเพลย์ลิสต์ขนาดใหญ่',
        'Download Auto-Generated Mixes': 'ดาวน์โหลดมิกซ์ที่สร้างอัตโนมัติ',
        'Ideal for Educators and Students': 'เหมาะสำหรับครูและนักเรียน',
        'Handling Unavailable or Private Videos': 'จัดการวิดีโอที่ไม่พร้อมใช้งานหรือส่วนตัว',
        'How to Download a Full Playlist': 'วิธีดาวน์โหลดเพลย์ลิสต์ทั้งหมด',
        'FAQ': 'คำถามที่พบบ่อย',
        'youtube playlist downloader, playlist to mp3, youtube playlist to mp4, batch youtube converter': 'youtube playlist downloader, playlist to mp3, youtube playlist to mp4, batch youtube converter, ดาวน์โหลดเพลย์ลิสต์ youtube, เพลย์ลิสต์เป็น mp3',
    },
    'tr': {  # Turkish
        'Home': 'Ana Sayfa',
        'Convert an entire YouTube playlist to MP3 or MP4 in one click. Each video downloads as its own file.': 'Tüm YouTube oynatma listesini tek tıklamayla MP3 veya MP4\'e dönüştürün. Her video kendi dosyası olarak indirilir.',
        'YT2MP3 - YouTube to MP3': 'YT2MP3 - YouTube\'dan MP3\'e',
        'Paste YouTube URL or search keywords': 'YouTube URL\'sini yapıştırın veya anahtar kelime arayın',
        'Paste a YouTube link': 'YouTube bağlantısını yapıştırın',
        'Paste from clipboard': 'Panodan yapıştır',
        'Paste': 'Yapıştır',
        'Output format': 'Çıktı formatı',
        'Quality': 'Kalite',
        'Audio track': 'Ses parçası',
        'Origin': 'Orijinal',
        'Search languages...': 'Dil ara...',
        'Origin (default)': 'Orijinal (varsayılan)',
        'Convert': 'Dönüştür',
        'Bulk-convert every video in a playlist': 'Oynatma listesindeki her videoyu toplu dönüştür',
        'Supports mixes and topic playlists': 'Karışımları ve konu oynatma listelerini destekler',
        'Picking the right format': 'Doğru formatı seçme',
        'Format Comparison Table': 'Format Karşılaştırma Tablosu',
        'Format': 'Format',
        'Best For': 'En İyi Kullanım',
        'Quality Options': 'Kalite Seçenekleri',
        'File Size': 'Dosya Boyutu',
        'Universal audio playback': 'Evrensel ses çalma',
        'Small': 'Küçük',
        'Video playback everywhere': 'Her yerde video oynatma',
        'Large': 'Büyük',
        'Lossless audio editing': 'Kayıpsız ses düzenleme',
        'Very Large': 'Çok Büyük',
        'Apple devices': 'Apple cihazları',
        'Medium': 'Orta',
        'Batch Conversion Masterclass': 'Toplu Dönüştürme Usta Sınıfı',
        'Preserve Original Order and Titles': 'Orijinal Sıra ve Başlıkları Koru',
        'Flexible Format Selection for Playlists': 'Oynatma Listeleri için Esnek Format Seçimi',
        'High-Concurrency Processing': 'Yüksek Eşzamanlı İşleme',
        'Support for Massive Playlists': 'Büyük Oynatma Listeleri Desteği',
        'Download Auto-Generated Mixes': 'Otomatik Oluşturulan Karışımları İndir',
        'Ideal for Educators and Students': 'Eğitimciler ve Öğrenciler için İdeal',
        'Handling Unavailable or Private Videos': 'Kullanılamayan veya Özel Videoları İşleme',
        'How to Download a Full Playlist': 'Tam Oynatma Listesi Nasıl İndirilir',
        'FAQ': 'SSS',
        'youtube playlist downloader, playlist to mp3, youtube playlist to mp4, batch youtube converter': 'youtube playlist downloader, playlist to mp3, youtube playlist to mp4, batch youtube converter, youtube oynatma listesi indir, oynatma listesini mp3\'e',
    },
    'ur': {  # Urdu (RTL)
        'Home': 'ہوم',
        'Convert an entire YouTube playlist to MP3 or MP4 in one click. Each video downloads as its own file.': 'ایک کلک میں مکمل YouTube پلے لسٹ کو MP3 یا MP4 میں تبدیل کریں۔ ہر ویڈیو اپنی الگ فائل کے طور پر ڈاؤن لوڈ ہوتی ہے۔',
        'YT2MP3 - YouTube to MP3': 'YT2MP3 - YouTube سے MP3',
        'Paste YouTube URL or search keywords': 'YouTube URL پیسٹ کریں یا مطلوبہ الفاظ تلاش کریں',
        'Paste a YouTube link': 'YouTube لنک پیسٹ کریں',
        'Paste from clipboard': 'کلپ بورڈ سے پیسٹ کریں',
        'Paste': 'پیسٹ',
        'Output format': 'آؤٹ پٹ فارمیٹ',
        'Quality': 'معیار',
        'Audio track': 'آڈیو ٹریک',
        'Origin': 'اصل',
        'Search languages...': 'زبانیں تلاش کریں...',
        'Origin (default)': 'اصل (ڈیفالٹ)',
        'Convert': 'تبدیل کریں',
        'Bulk-convert every video in a playlist': 'پلے لسٹ میں ہر ویڈیو کو بلک تبدیل کریں',
        'Supports mixes and topic playlists': 'مکسز اور موضوعاتی پلے لسٹس کی حمایت کرتا ہے',
        'Picking the right format': 'صحیح فارمیٹ کا انتخاب',
        'Format Comparison Table': 'فارمیٹ موازنہ جدول',
        'Format': 'فارمیٹ',
        'Best For': 'بہترین استعمال',
        'Quality Options': 'معیار کے اختیارات',
        'File Size': 'فائل سائز',
        'Universal audio playback': 'عالمگیر آڈیو پلے بیک',
        'Small': 'چھوٹا',
        'Video playback everywhere': 'ہر جگہ ویڈیو پلے بیک',
        'Large': 'بڑا',
        'Lossless audio editing': 'بغیر نقصان آڈیو ایڈیٹنگ',
        'Very Large': 'بہت بڑا',
        'Apple devices': 'Apple ڈیوائسز',
        'Medium': 'درمیانہ',
        'Batch Conversion Masterclass': 'بیچ تبدیلی ماسٹر کلاس',
        'Preserve Original Order and Titles': 'اصل ترتیب اور عنوانات محفوظ رکھیں',
        'Flexible Format Selection for Playlists': 'پلے لسٹس کے لیے لچکدار فارمیٹ انتخاب',
        'High-Concurrency Processing': 'اعلیٰ ہم وقتی پروسیسنگ',
        'Support for Massive Playlists': 'بڑی پلے لسٹس کی حمایت',
        'Download Auto-Generated Mixes': 'خودکار تیار شدہ مکسز ڈاؤن لوڈ کریں',
        'Ideal for Educators and Students': 'اساتذہ اور طلباء کے لیے مثالی',
        'Handling Unavailable or Private Videos': 'غیر دستیاب یا نجی ویڈیوز کو سنبھالنا',
        'How to Download a Full Playlist': 'مکمل پلے لسٹ کیسے ڈاؤن لوڈ کریں',
        'FAQ': 'عمومی سوالات',
        'youtube playlist downloader, playlist to mp3, youtube playlist to mp4, batch youtube converter': 'youtube playlist downloader, playlist to mp3, youtube playlist to mp4, batch youtube converter, یوٹیوب پلے لسٹ ڈاؤن لوڈ, پلے لسٹ کو mp3 میں',
    },
    'vi': {  # Vietnamese
        'Home': 'Trang chủ',
        'Convert an entire YouTube playlist to MP3 or MP4 in one click. Each video downloads as its own file.': 'Chuyển đổi toàn bộ danh sách phát YouTube sang MP3 hoặc MP4 chỉ bằng một cú nhấp chuột. Mỗi video tải xuống dưới dạng tệp riêng.',
        'YT2MP3 - YouTube to MP3': 'YT2MP3 - YouTube sang MP3',
        'Paste YouTube URL or search keywords': 'Dán URL YouTube hoặc tìm kiếm từ khóa',
        'Paste a YouTube link': 'Dán liên kết YouTube',
        'Paste from clipboard': 'Dán từ clipboard',
        'Paste': 'Dán',
        'Output format': 'Định dạng đầu ra',
        'Quality': 'Chất lượng',
        'Audio track': 'Bản nhạc âm thanh',
        'Origin': 'Gốc',
        'Search languages...': 'Tìm kiếm ngôn ngữ...',
        'Origin (default)': 'Gốc (mặc định)',
        'Convert': 'Chuyển đổi',
        'Bulk-convert every video in a playlist': 'Chuyển đổi hàng loạt mọi video trong danh sách phát',
        'Supports mixes and topic playlists': 'Hỗ trợ mix và danh sách phát chủ đề',
        'Picking the right format': 'Chọn định dạng phù hợp',
        'Format Comparison Table': 'Bảng So Sánh Định Dạng',
        'Format': 'Định dạng',
        'Best For': 'Tốt nhất cho',
        'Quality Options': 'Tùy chọn chất lượng',
        'File Size': 'Kích thước tệp',
        'Universal audio playback': 'Phát âm thanh phổ quát',
        'Small': 'Nhỏ',
        'Video playback everywhere': 'Phát video mọi nơi',
        'Large': 'Lớn',
        'Lossless audio editing': 'Chỉnh sửa âm thanh không mất dữ liệu',
        'Very Large': 'Rất lớn',
        'Apple devices': 'Thiết bị Apple',
        'Medium': 'Trung bình',
        'Batch Conversion Masterclass': 'Lớp học chuyển đổi hàng loạt',
        'Preserve Original Order and Titles': 'Giữ nguyên thứ tự và tiêu đề gốc',
        'Flexible Format Selection for Playlists': 'Lựa chọn định dạng linh hoạt cho danh sách phát',
        'High-Concurrency Processing': 'Xử lý đồng thời cao',
        'Support for Massive Playlists': 'Hỗ trợ danh sách phát lớn',
        'Download Auto-Generated Mixes': 'Tải xuống mix tự động tạo',
        'Ideal for Educators and Students': 'Lý tưởng cho giáo viên và học sinh',
        'Handling Unavailable or Private Videos': 'Xử lý video không khả dụng hoặc riêng tư',
        'How to Download a Full Playlist': 'Cách tải xuống danh sách phát đầy đủ',
        'FAQ': 'Câu hỏi thường gặp',
        'youtube playlist downloader, playlist to mp3, youtube playlist to mp4, batch youtube converter': 'youtube playlist downloader, playlist to mp3, youtube playlist to mp4, batch youtube converter, tải danh sách phát youtube, danh sách phát sang mp3',
    },
}

def translate_file(lang_code, file_path):
    """Translate a single file"""
    trans = translations.get(lang_code, {})
    if not trans:
        print(f"No translations for {lang_code}")
        return
    
    content = Path(file_path).read_text(encoding='utf-8')
    
    # Apply translations
    for en, translated in trans.items():
        content = content.replace(en, translated)
    
    # Write back
    Path(file_path).write_text(content, encoding='utf-8')
    print(f"✓ Translated {file_path}")

# Translate all remaining languages
langs = ['ja', 'ko', 'ru', 'th', 'tr', 'ur', 'vi']

for lang in langs:
    file_path = f'web/{lang}/youtube-playlist-downloader/index.html'
    translate_file(lang, file_path)

print("\n✅ All remaining languages translated!")
